"""Generate `backend/.env.example` and `docs/configuration.md` from the registry.

Run it after adding or changing a `Settings` field:

    backend/.venv/Scripts/python.exe -m backend.scripts.gen_config_docs
    backend/.venv/Scripts/python.exe -m backend.scripts.gen_config_docs --check

`--check` regenerates into memory and compares, exiting non-zero on a
difference. `backend/tests/test_service_config_docs.py` runs exactly that, so a
new setting cannot reach a buyer undocumented — which is how the example file
came to describe 20 of 45 variables in the first place.

Both outputs are English. `.env.example` is read by whoever deploys and
`docs/configuration.md` is the same reference in prose — an operator's manual,
not end-user copy, and the same audience as the source they are buying. Keeping
them in one language also keeps this generator free of Spanish string literals,
which `test_no_spanish_in_backend_logic.py` requires of every backend module.
The Spanish a USER reads lives in `Frontend/src/i18n/serviceConfig.ts`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from backend.service_config.registry import (
    SERVICES,
    ConfigField,
    Service,
    editable_fields,
    required_fields,
    requirement_groups,
)

ROOT = Path(__file__).resolve().parents[2]
ENV_EXAMPLE = ROOT / "backend" / ".env.example"
CONFIG_DOC = ROOT / "docs" / "configuration.md"

BANNER = "# Generated by backend/scripts/gen_config_docs.py — edit the registry, not this file."


def _wrap(text: str, width: int = 76, prefix: str = "# ") -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) + len(prefix) > width and current:
            lines.append(prefix + current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(prefix + current)
    return lines


def _env_block(service: Service) -> list[str]:
    out: list[str] = ["", "# " + "─" * 74, f"# {service.key.upper()} — {service.summary}"]
    out += _wrap(f"Without it: {service.what_breaks}")
    if service.docs_note:
        out += ["#"] + _wrap(service.docs_note.replace("\n\n", " ").replace("\n", " "))
    groups = requirement_groups(service)
    if groups:
        ways = " OR ".join(
            " + ".join(f.env for f in group) for group in groups
        )
        out += ["#"] + _wrap(f"Enough to turn it on: {ways}.")
    if service.tenant_scoped:
        out += ["#"] + _wrap(
            "A single tenant may override these from the app with its own "
            "sender; what is set here is the default for everyone else."
        )
    instance_only = [f.env for f in service.fields if f.instance_only]
    if instance_only and service.tenant_scoped:
        out += ["#"] + _wrap(
            "Not per tenant, even here: " + ", ".join(instance_only)
            + " — they are read before the tenant is known."
        )
    if not service.editable:
        out += ["#"] + _wrap("Environment only — the panel reports these, never writes them.")
    out += ["# " + "─" * 74]

    for f in service.fields:
        out += _wrap(f.doc)
        flags = []
        if f.required:
            flags.append("required for this service")
        if f.secret:
            flags.append("secret")
        if f.default:
            flags.append(f"default: {f.default}")
        if not f.editable:
            flags.append("environment only")
        if flags:
            out += _wrap("(" + "; ".join(flags) + ")")
        value = f.example if f.example else ""
        # Required fields are left uncommented so a copied file fails loudly on
        # the one thing that must be filled in, rather than booting with a
        # default nobody chose.
        prefix = "" if f.required and service.kind == "core" else "# "
        out.append(f"{prefix}{f.env}={value}")
        out.append("")
    return out


def render_env_example() -> str:
    lines = [
        BANNER,
        "#",
        "# Copy to backend/.env and fill in what you need.",
        "#",
        "# Only the CORE block is required. Every other service is optional: with",
        "# its variables empty the feature reports itself off and says so on the",
        "# screen that would have used it — nothing crashes, nothing pretends.",
        "# Each block below states exactly what stops working.",
        "#",
        "# Everything except CORE and the blocks marked 'environment only' can",
        "# also be set from the app at /instalacion, which stores it encrypted in",
        "# the database and takes effect without a restart. The database value",
        "# wins over this file, and the panel says which one is in effect.",
    ]
    for service in SERVICES:
        lines += _env_block(service)
    return "\n".join(lines).rstrip() + "\n"


def _field_row(f: ConfigField) -> str:
    flags = []
    if f.required:
        flags.append("required")
    if f.secret:
        flags.append("secret")
    if not f.editable:
        flags.append("environment only")
    default = f"`{f.default}`" if f.default else "-"
    return (
        f"| `{f.env}` | {default} | {', '.join(flags) or '-'} | "
        f"{f.doc.replace('|', '/')} |"
    )


def render_config_doc() -> str:
    lines = [
        "<!-- " + BANNER[2:] + " -->",
        "",
        "# Configuration - what Faro needs, and what stops working without it",
        "",
        "Generated from `backend/service_config/registry.py`, which is the only",
        "source of truth. A variable that is not here does not exist.",
        "",
        "## The two layers",
        "",
        "1. **The environment** (`backend/.env`, or real environment variables).",
        "   It is the floor: the database, the signing key and the deployment",
        "   switches are read from there and nowhere else.",
        "2. **The panel at `/instalacion`**, which stores everything else",
        "   encrypted in the database and takes effect without a restart. **The",
        "   stored value wins over the file**, and the panel says which one is in",
        "   effect for every field.",
        "",
        "Who may open that panel is NOT the `admin` role. `admin` exists inside a",
        "tenant and every company that signs up has one, so it cannot grant access",
        "to the deployment credentials; the addresses in `INSTANCE_ADMIN_EMAILS`",
        "can. With that variable empty nobody edits instance configuration from",
        "the app, and the panel says so, naming the variable. A tenant admin still",
        "configures its OWN channels - the sender its people and suppliers see.",
        "",
        "## The rule every optional service keeps",
        "",
        "Without its credential a service **turns off and says so**. No 500, no",
        "blank screen, and no answer quietly supplied by a different provider: the",
        "feature reports itself unavailable and the rest of the product carries on.",
        "",
        "The Spanish a user reads is not here - it lives in the app catalogue",
        "(`Frontend/src/i18n/serviceConfig.ts`). This file is for whoever deploys",
        "and operates the installation.",
        "",
    ]

    for service in SERVICES:
        kind_label = {
            "core": "core",
            "external": "external service",
            "deployment": "deployment",
        }[service.kind]
        lines += [
            f"## `{service.key}` - {service.summary}",
            "",
            f"*Kind:* {kind_label}. "
            f"*Editable from the panel:* {'yes' if service.editable else 'no'}. "
            f"*Per tenant:* {'yes' if service.tenant_scoped else 'no'}. "
            f"*Connection test:* {'yes' if service.probe else 'no'}.",
            "",
            f"**What is lost without it:** {service.what_breaks}",
            "",
        ]
        req = required_fields(service)
        if req:
            lines += [
                "**Minimum to turn it on:** "
                + ", ".join(f"`{f.env}`" for f in req),
                "",
            ]
        groups = requirement_groups(service)
        if groups:
            # An OR, not an AND: naming one path as "the" requirement would
            # send a reader hunting for a Resend account they do not need.
            ways = " **or** ".join(
                " + ".join(f"`{f.env}`" for f in group) for group in groups
            )
            lines += [f"**Any one of these is enough:** {ways}", ""]
        if service.docs_note:
            lines += [service.docs_note, ""]
        lines += [
            "| Variable | Default | Notes | What it does |",
            "|---|---|---|---|",
        ]
        for f in service.fields:
            lines.append(_field_row(f))
        if service.borrows:
            lines += [
                "",
                "It also uses, without duplicating them: "
                + ", ".join(f"`{k}`" for k in service.borrows)
                + ".",
            ]
        if service.editable:
            editable = editable_fields(service)
            if editable:
                lines += [
                    "",
                    "Writable from the panel: "
                    + ", ".join(f"`{f.env}`" for f in editable)
                    + ".",
                ]
            if service.tenant_scoped:
                instance_only = [f for f in editable if f.instance_only]
                if instance_only:
                    lines += [
                        "",
                        "A tenant may NOT take over: "
                        + ", ".join(f"`{f.env}`" for f in instance_only)
                        + " - they are read before the tenant is known, so a "
                        "per-tenant value would be read by nobody.",
                    ]
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Fail instead of writing when the files are out of date.",
    )
    args = parser.parse_args()

    targets = [(ENV_EXAMPLE, render_env_example()), (CONFIG_DOC, render_config_doc())]

    if args.check:
        stale = []
        for path, content in targets:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current.replace("\r\n", "\n") != content:
                stale.append(path)
        if stale:
            print("Out of date with the registry:")
            for path in stale:
                print(f"  {path.relative_to(ROOT)}")
            print("Run: python -m backend.scripts.gen_config_docs")
            return 1
        print("Configuration documentation is current.")
        return 0

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
