"""Generate `backend/.env.example` and `docs/configuracion.md` from the registry.

Run it after adding or changing a `Settings` field:

    backend/.venv/Scripts/python.exe -m backend.scripts.gen_config_docs
    backend/.venv/Scripts/python.exe -m backend.scripts.gen_config_docs --check

`--check` regenerates into memory and compares, exiting non-zero on a
difference. `backend/tests/test_service_config_docs.py` runs exactly that, so a
new setting cannot reach a buyer undocumented — which is how the example file
came to describe 20 of 45 variables in the first place.

Both outputs are English: `.env.example` is read by whoever deploys, and
`docs/configuracion.md` is the operator's manual, not end-user copy.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from backend.service_config.registry import (
    SERVICES,
    ConfigField,
    Service,
    editable_fields,
    required_fields,
    requirement_groups,
)

ROOT = Path(__file__).resolve().parents[2]
ENV_EXAMPLE = ROOT / "backend" / ".env.example"
CONFIG_DOC = ROOT / "docs" / "configuracion.md"

BANNER = "# Generated by backend/scripts/gen_config_docs.py — edit the registry, not this file."


def _wrap(text: str, width: int = 76, prefix: str = "# ") -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) + len(prefix) > width and current:
            lines.append(prefix + current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(prefix + current)
    return lines


def _env_block(service: Service) -> list[str]:
    out: list[str] = ["", "# " + "─" * 74, f"# {service.key.upper()} — {service.summary}"]
    out += _wrap(f"Without it: {service.what_breaks}")
    if service.docs_note:
        out += ["#"] + _wrap(service.docs_note.replace("\n\n", " ").replace("\n", " "))
    groups = requirement_groups(service)
    if groups:
        ways = " OR ".join(
            " + ".join(f.env for f in group) for group in groups
        )
        out += ["#"] + _wrap(f"Enough to turn it on: {ways}.")
    if service.tenant_scoped:
        out += ["#"] + _wrap(
            "A single tenant may override these from the app with its own "
            "sender; what is set here is the default for everyone else."
        )
    instance_only = [f.env for f in service.fields if f.instance_only]
    if instance_only and service.tenant_scoped:
        out += ["#"] + _wrap(
            "Not per tenant, even here: " + ", ".join(instance_only)
            + " — they are read before the tenant is known."
        )
    if not service.editable:
        out += ["#"] + _wrap("Environment only — the panel reports these, never writes them.")
    out += ["# " + "─" * 74]

    for f in service.fields:
        out += _wrap(f.doc)
        flags = []
        if f.required:
            flags.append("required for this service")
        if f.secret:
            flags.append("secret")
        if f.default:
            flags.append(f"default: {f.default}")
        if not f.editable:
            flags.append("environment only")
        if flags:
            out += _wrap("(" + "; ".join(flags) + ")")
        value = f.example if f.example else ""
        # Required fields are left uncommented so a copied file fails loudly on
        # the one thing that must be filled in, rather than booting with a
        # default nobody chose.
        prefix = "" if f.required and service.kind == "core" else "# "
        out.append(f"{prefix}{f.env}={value}")
        out.append("")
    return out


def render_env_example() -> str:
    lines = [
        BANNER,
        "#",
        "# Copy to backend/.env and fill in what you need.",
        "#",
        "# Only the CORE block is required. Every other service is optional: with",
        "# its variables empty the feature reports itself off and says so on the",
        "# screen that would have used it — nothing crashes, nothing pretends.",
        "# Each block below states exactly what stops working.",
        "#",
        "# Everything except CORE and the blocks marked 'environment only' can",
        "# also be set from the app at /instalacion, which stores it encrypted in",
        "# the database and takes effect without a restart. The database value",
        "# wins over this file, and the panel says which one is in effect.",
    ]
    for service in SERVICES:
        lines += _env_block(service)
    return "\n".join(lines).rstrip() + "\n"


def _field_row(f: ConfigField) -> str:
    flags = []
    if f.required:
        flags.append("requerida")
    if f.secret:
        flags.append("secreta")
    if not f.editable:
        flags.append("solo entorno")
    default = f"`{f.default}`" if f.default else "—"
    return (
        f"| `{f.env}` | {default} | {', '.join(flags) or '—'} | "
        f"{f.doc.replace('|', '/')} |"
    )


def render_config_doc() -> str:
    lines = [
        "<!-- " + BANNER[2:] + " -->",
        "",
        "# Configuración — qué necesita Faro y qué deja de funcionar sin ello",
        "",
        "Este documento se genera desde `backend/service_config/registry.py`, que",
        "es la única fuente de verdad. Si una variable no está aquí, no existe.",
        "",
        "## Las dos capas",
        "",
        "1. **El entorno** (`backend/.env` o variables reales). Es el piso: la base",
        "   de datos, la llave de firma y el modo de despliegue solo se leen de ahí.",
        "2. **El panel `/instalacion`**, que guarda lo demás cifrado en la base y",
        "   toma efecto sin reiniciar. **La base gana sobre el entorno**, y el panel",
        "   dice cuál está mandando para cada campo.",
        "",
        "Quién puede abrir ese panel no es el rol `admin` —que existe dentro de cada",
        "tenant— sino las direcciones listadas en `INSTANCE_ADMIN_EMAILS`. Con esa",
        "variable vacía nadie edita la configuración de la instancia desde la app, y",
        "el panel lo dice nombrando la variable. Un tenant sí puede configurar sus",
        "propios canales (su remitente de correo y su número de WhatsApp).",
        "",
        "## Regla que cumple todo lo opcional",
        "",
        "Sin su credencial, un servicio **se apaga y lo dice**. No hay 500, no hay",
        "pantalla en blanco y no hay respuesta inventada por otro proveedor: la",
        "función informa que está fuera de servicio y el resto de la aplicación",
        "sigue funcionando.",
        "",
    ]

    for service in SERVICES:
        kind_label = {
            "core": "núcleo",
            "external": "servicio externo",
            "deployment": "despliegue",
        }[service.kind]
        lines += [
            f"## `{service.key}` — {service.summary}",
            "",
            f"*Tipo:* {kind_label}. "
            f"*Editable desde el panel:* {'sí' if service.editable else 'no'}. "
            f"*Por tenant:* {'sí' if service.tenant_scoped else 'no'}. "
            f"*Prueba de conexión:* {'sí' if service.probe else 'no'}.",
            "",
            f"**Qué se pierde sin esto:** {service.what_breaks}",
            "",
        ]
        req = required_fields(service)
        if req:
            lines += [
                "**Mínimo para que encienda:** "
                + ", ".join(f"`{f.env}`" for f in req),
                "",
            ]
        groups = requirement_groups(service)
        if groups:
            # An OR, not an AND: naming one path as "the" requirement would
            # send a reader hunting for a Resend account they do not need.
            ways = " **o bien** ".join(
                " + ".join(f"`{f.env}`" for f in group) for group in groups
            )
            lines += [f"**Basta con una de estas:** {ways}", ""]
        if service.docs_note:
            lines += [service.docs_note, ""]
        lines += [
            "| Variable | Default | Notas | Qué hace |",
            "|---|---|---|---|",
        ]
        for f in service.fields:
            lines.append(_field_row(f))
        if service.borrows:
            lines += [
                "",
                "Además usa, sin duplicarlas: "
                + ", ".join(f"`{k}`" for k in service.borrows)
                + ".",
            ]
        if service.editable:
            editable = editable_fields(service)
            if editable:
                lines += [
                    "",
                    "Desde el panel se pueden escribir: "
                    + ", ".join(f"`{f.env}`" for f in editable)
                    + ".",
                ]
            if service.tenant_scoped:
                instance_only = [f for f in editable if f.instance_only]
                if instance_only:
                    lines += [
                        "",
                        "Un tenant NO puede tomar: "
                        + ", ".join(f"`{f.env}`" for f in instance_only)
                        + " — se leen antes de saber de qué tenant viene el "
                        "mensaje, así que un valor por tenant no lo leería nadie.",
                    ]
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Fail instead of writing when the files are out of date.",
    )
    args = parser.parse_args()

    targets = [(ENV_EXAMPLE, render_env_example()), (CONFIG_DOC, render_config_doc())]

    if args.check:
        stale = []
        for path, content in targets:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current.replace("\r\n", "\n") != content:
                stale.append(path)
        if stale:
            print("Out of date with the registry:")
            for path in stale:
                print(f"  {path.relative_to(ROOT)}")
            print("Run: python -m backend.scripts.gen_config_docs")
            return 1
        print("Configuration documentation is current.")
        return 0

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
