"""Generate backend-rs/src/routes/w2b/tenant_tables.rs from the Python source.

The whole-tenant erasure list and the export column lists are DATA in
`backend/tenants/data_export.py`. The Rust port must erase exactly the same
tables, in the same order, and export exactly the same columns, so it never
re-types them: this script reads the Python module with `ast` (no import, no
database) and writes the Rust constants.

    python scripts/gen_rust_tenant_tables.py            # rewrite the file
    python scripts/gen_rust_tenant_tables.py --check    # exit 1 when stale

The contract harness (tests/contract/contract_test.py) runs the same check, so
a change to the Python lists that is not regenerated shows up as a failure.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "backend" / "tenants" / "data_export.py"
TARGET = ROOT / "backend-rs" / "src" / "routes" / "w2b" / "tenant_tables.rs"

HEADER = (
    "//! GENERATED by scripts/gen_rust_tenant_tables.py from\n"
    "//! backend/tenants/data_export.py. Do not edit: change the Python lists and\n"
    "//! regenerate (`python scripts/gen_rust_tenant_tables.py`). The contract\n"
    "//! harness fails when this file is stale.\n\n"
)


def _literals() -> dict:
    tree = ast.parse(SOURCE.read_text(encoding="utf-8"))
    wanted = {"_EXPORT_SPECS", "_DELETE_ORDER", "_STORAGE_CATEGORIES", "_OMITTED_FROM_EXPORT"}
    found = {}
    for node in tree.body:
        target = None
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target = node.target.id
        elif isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
            target = node.targets[0].id
        if target in wanted:
            found[target] = ast.literal_eval(node.value)
    missing = wanted - set(found)
    if missing:
        raise SystemExit(f"data_export.py no longer defines {sorted(missing)}")
    return found


def _s(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    lit = _literals()
    out = [HEADER]
    out.append("/// `_EXPORT_SPECS`: (file stem, table, SELECT column list; `*` = every column).\n")
    out.append("pub const EXPORT_SPECS: &[(&str, &str, &str)] = &[\n")
    for stem, table, cols in lit["_EXPORT_SPECS"]:
        out.append(f"    ({_s(stem)}, {_s(table)}, {_s(cols)}),\n")
    out.append("];\n\n")
    out.append("/// `_OMITTED_FROM_EXPORT`.\npub const OMITTED_FROM_EXPORT: &[&str] = &[\n")
    for t in lit["_OMITTED_FROM_EXPORT"]:
        out.append(f"    {_s(t)},\n")
    out.append("];\n\n")
    out.append("/// `_DELETE_ORDER`: children before parents, one transaction.\n")
    out.append("pub const DELETE_ORDER: &[&str] = &[\n")
    for t in lit["_DELETE_ORDER"]:
        out.append(f"    {_s(t)},\n")
    out.append("];\n\n")
    out.append("/// `_STORAGE_CATEGORIES`: `storage/<category>/<tenant_id>` is removed per entry.\n")
    out.append("pub const STORAGE_CATEGORIES: &[&str] = &[\n")
    for t in lit["_STORAGE_CATEGORIES"]:
        out.append(f"    {_s(t)},\n")
    out.append("];\n")
    return "".join(out)


def is_current() -> bool:
    if not TARGET.exists():
        return False
    return TARGET.read_text(encoding="utf-8").replace("\r\n", "\n") == render()


def main() -> int:
    if "--check" in sys.argv:
        if is_current():
            print("tenant_tables.rs is current")
            return 0
        print("tenant_tables.rs is STALE: run python scripts/gen_rust_tenant_tables.py")
        return 1
    TARGET.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
