import type { TourDefinition } from '../types'

export const analystTour: TourDefinition = {
  id: 'analyst-v2',
  route: '/analyst',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'an.new', title: 'new_title', body: 'new_body' },
    { anchor: 'an.chats', title: 'chats_title', body: 'chats_body' },
    { anchor: 'an.chats', title: 'chat_actions_title', body: 'chat_actions_body' },
    { anchor: 'an.start', title: 'start_title', body: 'start_body' },
    { anchor: 'an.session', title: 'session_title', body: 'session_body' },
    { anchor: 'an.input', title: 'input_title', body: 'input_body' },
    { title: 'examples_title', body: 'examples_body' },
    { anchor: 'an.thread', title: 'badges_title', body: 'badges_body' },
    { anchor: 'an.sources', title: 'sources_title', body: 'sources_body' },
    { title: 'limits_title', body: 'limits_body' },
  ],
  copy: {
    es: {
      name: 'Cómo usar el analista',
      intro_title: 'Preguntar por tus números en palabras',
      intro_body: 'El analista responde sobre lo que ya está dentro de Faro: los resultados de una actualización, qué tan bien le atinó cada modelo a cada producto, tu inventario, la calidad de los datos que subiste.\n\nNo es un buscador de internet. Si algo nunca lo subiste, aquí no hay respuesta — y te lo va a decir en vez de inventarla.\n\nLa pantalla tiene pocas piezas: la lista de conversaciones a la izquierda, el selector de sesión arriba y el cuadro de escribir abajo. Vamos a ver qué hace cada una.',
      new_title: 'El botón + : una conversación por tema',
      new_body: 'Abre una conversación vacía. El título lo pone solo con tu primera pregunta, así que no tienes que nombrarla.\n\nCada conversación arrastra sus mensajes anteriores como contexto. Eso es lo que te deja repreguntar («¿y ese mismo producto en diciembre?») sin volver a explicarlo todo.\n\nY es justo lo que estorba cuando cambias de tema: si venías hablando de bebidas y preguntas por los proveedores, el hilo sigue cargando lo de antes y la respuesta sale contaminada. Cuando la pregunta no tenga nada que ver con la anterior, abre una nueva.',
      chats_title: 'La lista: lo que preguntaste no se pierde',
      chats_body: 'Cada conversación queda guardada con su última respuesta a la vista y la hora del último mensaje. Se ordenan por actividad: la que tocaste hace un minuto queda arriba.\n\nEl buscador de arriba filtra sólo por título — el que se generó con tu primera pregunta —, no por el contenido de los mensajes. Por eso la primera pregunta de cada hilo conviene que sea la de verdad, no un «hola».\n\nLa etiqueta verde RAG en una fila significa que esa conversación está mirando los datos de una actualización.',
      chat_actions_title: 'Estrella y basurero, al pasar el ratón',
      chat_actions_body: 'Al pasar el ratón sobre una conversación aparecen dos iconos a la derecha.\n\nLa estrella la sube al bloque de Favoritas, arriba del todo. Sirve para las tres o cuatro preguntas que repites cada mes; no cambia nada de la respuesta.\n\nEl basurero pide un segundo clic para confirmar. La conversación desaparece de la lista al instante y te queda una ventanita para deshacer desde el aviso de abajo. Si dejas pasar ese momento, se borra de verdad: los mensajes no se recuperan.',
      start_title: 'Cuando aún no hay ninguna conversación',
      start_body: 'Esto es lo que ves antes de abrir la primera: un botón que crea la conversación y nada más.\n\nTambién puedes escribir directamente en el cuadro de abajo dentro de una conversación nueva; si no hay ninguna abierta, se crea sola al enviar.\n\nY dentro de una conversación vacía verás unos botones ovalados con preguntas sugeridas. No son un menú cerrado: al tocar uno se escribe en el cuadro y puedes cambiarlo antes de enviar.',
      session_title: 'El selector «Sesión»: general o sobre tus datos',
      session_body: 'Aquí decides con qué responde la conversación, y la diferencia es grande.\n\nEn «— General —» contesta con conocimiento general: qué significa un término, cómo funciona la plataforma, cómo se lee una métrica. No mira tus datos, y si le preguntas por un SKU tuyo no lo va a conocer.\n\nElige una actualización completada y sí los mira: responde con tus productos, tus cifras y tus riesgos de quiebre, y aparece la etiqueta RAG.\n\nSólo salen las actualizaciones Completadas. Puedes cambiarlo a media charla: lo que sigue se responde con la nueva base, lo ya escrito no se reescribe.',
      input_title: 'El cuadro de escribir',
      input_body: 'Enter envía; Shift+Enter hace un salto de línea, para cuando quieras dar contexto en dos renglones.\n\nEscribe como le hablarías a un compañero, no como a un buscador: «¿por qué me pide 700 de SKU-008?» funciona mejor que «SKU-008 700». Menciona el código del producto tal como aparece en tus datos, porque con eso ubica la información exacta.\n\nUna pregunta por mensaje. Si mandas tres juntas suele contestar bien la primera y de refilón las otras dos.',
      examples_title: 'Preguntas que funcionan y preguntas que no',
      examples_body: 'Funcionan (con una sesión elegida): «¿por qué me pide 700 de SKU-008?», «¿qué productos tienen el pronóstico menos confiable?», «¿cuáles están en Pedir ya y de qué proveedor son?», «¿qué tan sucios venían los datos de SKU-014?».\n\nNo funcionan: «¿cuánto me va a costar el flete en marzo?» o «¿mi competencia bajó precios?» — eso nunca lo subiste, no está en Faro. Tampoco «¿qué compro?» a secas: demasiado vago para una respuesta útil.\n\nCuando no puede, lo dice. Una respuesta que empieza reconociendo que no tiene ese dato es la respuesta correcta, no una falla.',
      badges_title: 'La etiqueta debajo de cada respuesta',
      badges_body: 'Bajo cada respuesta, junto a la hora, hay una etiqueta que dice de dónde salió. Es el control de honestidad de esta pantalla:\n\nTus datos — leyó la actualización elegida.\nGeneral / Respuesta general — contestó sin leer tus datos.\nFuera de tema — tu pregunta no se parece a nada de esa actualización.\nSin acceso — esa actualización no tiene datos indexados para ti.\nTus datos (sin resumen) — encontró la información pero no pudo redactarla, así que te muestra el material crudo.\nError — la petición falló; vuelve a intentar.\n\nSi esperabas «Tus datos» y ves «General», revisa el selector de sesión antes de creerte la cifra.',
      sources_title: 'El filtro de fuentes',
      sources_body: 'Aparece sólo cuando la conversación está ligada a una actualización, y limita en qué material puede buscar: perfil de datos, resumen de modelos, resultados por producto, y demás. Lo verás dos veces —aquí arriba y junto al cuadro de escribir—: es el mismo control, no dos filtros distintos.\n\nDéjalo en «Todas» casi siempre. Sirve para acotar cuando una respuesta se te va por las ramas: si sólo te interesa la precisión de los modelos, marca esa fuente y el resto deja de estorbar.\n\nEl riesgo del filtro es dejarlo puesto y olvidarlo: después parece que el analista no sabe algo cuando en realidad le tapaste la fuente donde estaba.',
      limits_title: 'Para qué sirve y para qué no',
      limits_body: 'Sirve para entender en lenguaje normal los números detrás de una recomendación: por qué este producto salió urgente, qué tan confiable fue el pronóstico en él, qué tan sucios venían sus datos.\n\nNo reemplaza al semáforo, que ya te da la cobertura y la cantidad exactas, y sus respuestas no cambian ningún dato: no crea pedidos ni edita tus SKUs.\n\nY no compra nada. La decisión sigue siendo tuya; esto sólo te ahorra el rato de perseguir el número a mano.',
    },
    en: {
      name: 'How to use the analyst',
      intro_title: 'Ask about your numbers in plain words',
      intro_body: 'The analyst answers about what is already inside Faro: the results of an update, how well each model did on each product, your inventory, the quality of the data you uploaded.\n\nIt is not an internet search. If you never uploaded something, there is no answer here — and it will tell you so rather than make one up.\n\nThe screen has few pieces: the conversation list on the left, the session picker at the top and the message box at the bottom. We will go through what each one does.',
      new_title: 'The + button: one conversation per topic',
      new_body: 'It opens an empty conversation. The title writes itself from your first question, so there is nothing to name.\n\nEvery conversation carries its earlier messages along as context. That is what lets you follow up ("and that same product in December?") without explaining it all again.\n\nAnd it is exactly what gets in the way when you switch topics: if you were discussing drinks and then ask about suppliers, the thread keeps dragging the old subject along and the answer comes back contaminated. When the question has nothing to do with the last one, start a new one.',
      chats_title: 'The list: what you asked is not lost',
      chats_body: 'Every conversation is kept with its latest reply in view and the time of the last message. They sort by activity: the one you touched a minute ago sits on top.\n\nThe search box above filters by title only — the one generated from your first question — not by the content of the messages. Which is why the first question in a thread should be the real one, not a "hi".\n\nA green RAG tag on a row means that conversation is looking at the data of an update.',
      chat_actions_title: 'Star and bin, on hover',
      chat_actions_body: 'Hovering over a conversation reveals two icons on the right.\n\nThe star moves it into the Favourites block at the very top. It is for the three or four questions you repeat every month; it changes nothing about the answers.\n\nThe bin asks for a second click to confirm. The conversation leaves the list immediately and you get a short window to undo from the notice at the bottom. Let that moment pass and it is really gone: the messages do not come back.',
      start_title: 'When there is no conversation yet',
      start_body: 'This is what you see before opening the first one: a button that creates the conversation, and nothing else.\n\nYou can also type straight into the box below inside a new conversation; if none is open, one is created for you when you send.\n\nAnd inside an empty conversation you will see oval buttons with suggested questions. They are not a closed menu: tapping one writes it into the box and you can edit it before sending.',
      session_title: 'The "Session" picker: general, or about your data',
      session_body: 'This is where you decide what the conversation answers from, and the difference is a big one.\n\nOn "— General —" it answers from general knowledge: what a term means, how the platform works, how to read a metric. It does not look at your data, and if you ask about one of your SKUs it will not know it.\n\nPick a completed update and it does look: it answers with your products, your figures and your stockout risks, and the RAG tag appears.\n\nOnly Completed updates are listed. You can switch mid-chat: what follows is answered from the new base, what is already written is not rewritten.',
      input_title: 'The message box',
      input_body: 'Enter sends; Shift+Enter adds a line break, for when you want to give context over two lines.\n\nWrite as you would to a colleague, not to a search engine: "why is it asking me for 700 of SKU-008?" works better than "SKU-008 700". Mention the product code exactly as it appears in your data, because that is what pins down the right information.\n\nOne question per message. Send three at once and it usually answers the first one well and the other two in passing.',
      examples_title: 'Questions that work, and questions that cannot',
      examples_body: 'These work (with a session picked): "why is it asking me for 700 of SKU-008?", "which products have the least reliable forecast?", "which ones are on Order NOW and from which supplier?", "how dirty was the data for SKU-014?".\n\nThese do not: "what will freight cost me in March?" or "did my competitor cut prices?" — you never uploaded that, it is not in Faro. Nor a bare "what should I buy?": too vague for a useful answer.\n\nWhen it cannot, it says so. An answer that opens by admitting it does not have that data is the correct answer, not a failure.',
      badges_title: 'The tag under each answer',
      badges_body: 'Under every answer, next to the time, a tag says where it came from. It is the honesty check of this screen:\n\nYour data — it read the chosen update.\nGeneral / General answer — it answered without reading your data.\nOff topic — your question resembles nothing in that update.\nNo access — that update has no indexed data for you.\nYour data (no summary) — it found the information but could not write it up, so it shows you the raw material.\nError — the request failed; try again.\n\nIf you expected "Your data" and see "General", check the session picker before believing the figure.',
      sources_title: 'The sources filter',
      sources_body: 'It appears only when the conversation is tied to an update, and it limits which material can be searched: data profile, model summary, per-product results, and so on. You will see it twice — up here and next to the message box: it is the same control, not two different filters.\n\nLeave it on "All" nearly always. It is for narrowing things down when an answer wanders: if you only care about model accuracy, tick that source and the rest stops getting in the way.\n\nThe risk of the filter is setting it and forgetting it: afterwards it looks as if the analyst does not know something when in fact you covered up the source it was in.',
      limits_title: 'What it is for, and what it is not',
      limits_body: 'It is for understanding, in plain language, the numbers behind a recommendation: why this product came out urgent, how reliable the forecast was on it, how dirty its data was.\n\nIt does not replace the stock signal, which already gives you exact coverage and quantity, and its answers change no data: it creates no orders and edits none of your SKUs.\n\nAnd it buys nothing. The decision stays yours; this only saves you the time of chasing the number by hand.',
    },
  },
}
