import type { TourDefinition } from '../types'

// v3 (2026-10-01): the assistant now always answers from the account's live
// data, so the session picker and the sources filter this tour used to explain
// are gone from the screen — and their steps with them. Bumping the id shows
// the new tour once to people who had already dismissed the old one.
export const analystTour: TourDefinition = {
  id: 'analyst-v3',
  route: '/asistente',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'an.new', title: 'new_title', body: 'new_body' },
    { anchor: 'an.chats', title: 'chats_title', body: 'chats_body' },
    { anchor: 'an.chats', title: 'chat_actions_title', body: 'chat_actions_body' },
    { anchor: 'an.start', title: 'start_title', body: 'start_body' },
    { anchor: 'an.input', title: 'input_title', body: 'input_body' },
    { title: 'examples_title', body: 'examples_body' },
    { anchor: 'an.thread', title: 'badges_title', body: 'badges_body' },
    { title: 'limits_title', body: 'limits_body' },
  ],
  copy: {
    es: {
      name: 'Cómo usar el asistente',
      intro_title: 'Tu asistente conoce tu cuenta',
      intro_body: 'El asistente responde con los datos de tu empresa tal como están ahora: qué productos están en rojo y cuánto pedir, tus órdenes en camino o atrasadas, cómo te cumplen tus proveedores, cuánto dinero tienes parado en sobrestock y qué tan frescos están tus datos.\n\nNo es un buscador de internet. Si algo nunca lo subiste, te lo dice y te indica dónde cargarlo, en vez de inventarlo.\n\nEs el mismo asistente que te responde por WhatsApp.',
      new_title: 'El botón + : una conversación por tema',
      new_body: 'Abre una conversación vacía. El título lo pone solo con tu primera pregunta.\n\nCada conversación arrastra sus mensajes anteriores como contexto: por eso puedes repreguntar («¿y a quién se lo pido?») sin explicarlo todo de nuevo. Cuando cambies de tema, abre una nueva.',
      chats_title: 'La lista: lo que preguntaste no se pierde',
      chats_body: 'Cada conversación queda guardada con su última pregunta a la vista y la hora del último mensaje. Se ordenan por actividad.\n\nEl buscador filtra sólo por título — el que se generó con tu primera pregunta —, no por el contenido de los mensajes.',
      chat_actions_title: 'Estrella y basurero, al pasar el ratón',
      chat_actions_body: 'Al pasar el ratón sobre una conversación aparecen dos iconos a la derecha.\n\nLa estrella la sube al bloque de Favoritas. El basurero pide un segundo clic para confirmar; tienes una ventanita para deshacer desde el aviso de abajo. Si la dejas pasar, los mensajes no se recuperan.',
      start_title: 'Preguntas hechas con tus datos',
      start_body: 'Arriba te saluda por tu nombre y te resume el día: cuántos productos están para pedir ya, cuántos para pedir pronto y si hay órdenes atrasadas.\n\nLas preguntas sugeridas salen de tu cuenta — por ejemplo, el producto que está más en rojo hoy. Al tocar una se envía directo; no hace falta crear la conversación antes.',
      input_title: 'El cuadro de escribir',
      input_body: 'Enter envía; Shift+Enter hace un salto de línea.\n\nEscribe como le hablarías a un compañero: «¿por qué el aceite de oliva está en rojo?» funciona; puedes nombrar el producto como lo llamas tú o por su código.\n\nUna pregunta por mensaje responde mejor que tres juntas.',
      examples_title: 'Preguntas que funcionan y preguntas que no',
      examples_body: 'Funcionan: «¿qué debo comprar hoy y a quién?», «¿qué pasa con la orden OC-000012?», «¿qué tan cumplido es mi proveedor X?», «¿cuánto dinero tengo parado en sobrestock?».\n\nNo funcionan: «¿cuánto me va a costar el flete en marzo?» o «¿mi competencia bajó precios?» — eso no está en StockAI.\n\nTampoco puede hacer cosas por ti: no crea, envía ni recibe órdenes. Te dice qué haría y en qué pantalla se hace.',
      badges_title: 'La etiqueta debajo de cada respuesta',
      badges_body: 'Bajo cada respuesta hay una etiqueta que dice cómo se armó:\n\nTus datos — la respondió el asistente y cada cifra coincide con tu cuenta.\nRevisa las cifras — algunas cifras no se pudieron comprobar contra tus datos; la respuesta las nombra al final.\nResumen de tus datos — no hubo respuesta con IA (no está activada o tardó demasiado), así que te muestra directamente lo que dicen tus datos.\nError — la petición falló; vuelve a intentar.',
      limits_title: 'Para qué sirve y para qué no',
      limits_body: 'Sirve para entender en lenguaje normal tu inventario y tus compras: por qué algo salió urgente, cuánto pedir y a quién, qué está atrasado.\n\nNo cambia ningún dato y no compra nada. La decisión sigue siendo tuya; esto sólo te ahorra perseguir el número a mano.',
    },
    en: {
      name: 'How to use the assistant',
      intro_title: 'Your assistant knows your account',
      intro_body: 'The assistant answers with your company\'s data as it is right now: which products are in the red and how much to order, your orders on the way or late, how reliable your suppliers are, how much money is tied up in overstock and how fresh your data is.\n\nIt is not an internet search. If you never uploaded something, it tells you so and where to load it, rather than make it up.\n\nIt is the same assistant that answers you on WhatsApp.',
      new_title: 'The + button: one conversation per topic',
      new_body: 'It opens an empty conversation. The title writes itself from your first question.\n\nEvery conversation carries its earlier messages as context: that is why you can follow up ("and who do I order it from?") without explaining it all again. When you switch topics, start a new one.',
      chats_title: 'The list: what you asked is not lost',
      chats_body: 'Every conversation is kept with its latest question in view and the time of the last message. They sort by activity.\n\nThe search box filters by title only — the one generated from your first question — not by the content of the messages.',
      chat_actions_title: 'Star and bin, on hover',
      chat_actions_body: 'Hovering over a conversation reveals two icons on the right.\n\nThe star moves it into the Favourites block. The bin asks for a second click to confirm; you get a short window to undo from the notice at the bottom. Let it pass and the messages do not come back.',
      start_title: 'Questions made from your data',
      start_body: 'At the top it greets you by name and sums up the day: how many products to order now, how many to order soon, and whether any order is late.\n\nThe suggested questions come from your account — for example, the product most in the red today. Tapping one sends it straight away; there is no need to create the conversation first.',
      input_title: 'The message box',
      input_body: 'Enter sends; Shift+Enter adds a line break.\n\nWrite as you would to a colleague: "why is the olive oil in the red?" works; you can name the product the way you call it or by its code.\n\nOne question per message answers better than three at once.',
      examples_title: 'Questions that work, and questions that cannot',
      examples_body: 'These work: "what should I buy today and from whom?", "what is going on with order OC-000012?", "how reliable is my supplier X?", "how much money is tied up in overstock?".\n\nThese do not: "what will freight cost me in March?" or "did my competitor cut prices?" — that is not in StockAI.\n\nNor can it do things for you: it does not create, send or receive orders. It tells you what it would do and on which screen that is done.',
      badges_title: 'The tag under each answer',
      badges_body: 'Under every answer a tag says how it was put together:\n\nYour data — the assistant answered and every figure matches your account.\nCheck the figures — some figures could not be verified against your data; the answer names them at the end.\nSummary of your data — there was no AI answer (not enabled, or too slow), so it shows you what your data says directly.\nError — the request failed; try again.',
      limits_title: 'What it is for, and what it is not',
      limits_body: 'It is for understanding your inventory and purchasing in plain language: why something came out urgent, how much to order and from whom, what is late.\n\nIt changes no data and buys nothing. The decision stays yours; this only saves you chasing the number by hand.',
    },
  },
}
