import type { TourDefinition } from '../types'

export const dataTour: TourDefinition = {
  id: 'data-v2',
  route: '/data',
  name: 'name',
  autoStart: true,
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'data.new', title: 'new_title', body: 'new_body' },
    { anchor: 'data.search', title: 'search_title', body: 'search_body' },
    { anchor: 'data.item', title: 'item_title', body: 'item_body' },
    { anchor: 'data.header', title: 'header_title', body: 'header_body' },
    { anchor: 'data.stats', title: 'stats_title', body: 'stats_body' },
    { anchor: 'data.tabs', title: 'tabs_title', body: 'tabs_body' },
    { anchor: 'data.content', title: 'content_title', body: 'content_body' },
    { title: 'ready_title', body: 'ready_body' },
  ],
  copy: {
    es: {
      name: 'Cómo preparar los datos de los que todo depende',
      intro_title: 'De aquí sale todo lo demás',
      intro_body: 'Esta pantalla es tu bodega de datos: los archivos y conexiones con los que se entrena todo lo que después lees como recomendación de compra.\n\nUn archivo mal armado casi nunca da un error. Da un pronóstico creíble y equivocado, que es mucho peor. Por eso el rato que pasas aquí rinde más que el que pasas ajustando modelos: es el único punto del flujo donde arreglas la causa en vez del síntoma.',
      new_title: '«Nuevo elemento»: archivo o conexión',
      new_body: 'Abre el panel de la derecha con dos opciones.\n\n«Subir archivo» acepta CSV y Excel: lo sueltas en la zona de carga y luego rellenas dos campos opcionales. En Nombre pon algo que se entienda dentro de seis meses — «Ventas 2024–2026», no «export_final(3)». En Descripción, de dónde salió y hasta qué fecha llega: «export del POS, hasta 30/06».\n\n«Base de datos SQL» te pide motor, host, puerto, base, usuario y contraseña. La diferencia real: el archivo es una foto del día que lo subiste y alguien tiene que reemplazarlo; la conexión se relee cada vez que entrenas.',
      search_title: 'Buscar fuentes',
      search_body: 'Filtra la lista de la izquierda por nombre mientras escribes. Con tres o cuatro archivos no hace falta; con veinte es la diferencia entre encontrar el correcto y entrenar sobre el de hace medio año.\n\nEs justo la razón por la que el nombre importa: si buscas «ventas» y te salen cinco fuentes llamadas «ventas», el buscador no te puede salvar. Nómbralas por período o por origen y esta caja se vuelve útil.\n\nEl número de arriba te dice cuántas fuentes tienes en total, y el ícono de refrescar vuelve a leer la lista del servidor.',
      item_title: 'La ficha de la lista, antes de fiarte del archivo',
      item_body: 'Cada fila trae la insignia de estado, el tamaño y el número de filas. Suena aburrido y es el filtro más barato que tienes.\n\nLo que buscas es una incoherencia: un archivo de ventas de dos años que pesa 12 KB está cortado; 300 filas para 200 productos es un mes escaso de historia, no un histórico; y una conexión en rojo dejó de responder y va a entrenar con lo último que alcanzó a leer.\n\nDescubrirlo ahora te cuesta un minuto. Descubrirlo después de entrenar te cuesta un ciclo de compras, porque el pronóstico va a salir igual y va a parecer razonable.',
      header_title: 'Renombrar, probar y borrar',
      header_body: 'El lápiz junto al título renombra la fuente: cambia sólo la etiqueta, no los datos, y es lo primero que deberías arreglar si heredaste un «datos (1).xlsx».\n\nDebajo va la insignia de estado y el nombre del archivo original, que es el que subiste — útil cuando el nombre bonito ya no se parece en nada.\n\nEn una conexión SQL aparece además «Probar conexión»: úsalo antes de entrenar, no después.\n\nEl bote de basura borra la fuente. Te pedimos confirmación porque los entrenamientos que se hicieron con ella se quedan sin su origen.',
      stats_title: 'Los cuatro números que valen una revisión',
      stats_body: 'Tamaño, filas, columnas y tipo. Léelos como una suma que tiene que cuadrar con lo que crees que subiste.\n\nSi esperabas 18 meses de ventas y ves 400 filas, la exportación se cortó. Si esperabas 6 columnas y hay 40, subiste el reporte completo del sistema y no la tabla de ventas — funciona igual, pero te va a costar más trabajo en el mapeo.\n\nY «Filas» vacío o en cero significa que no pudimos leer el contenido: casi siempre un Excel donde los datos no están en la primera hoja.',
      tabs_title: 'Las cuatro pestañas y para qué sirve cada una',
      tabs_body: '«Vista previa»: las primeras 100 filas tal cual las leemos nosotros. Es la única forma de ver lo que el sistema ve.\n\n«Editar»: corriges celdas, agregas o borras filas y columnas, le pones nombre y se guarda como una fuente nueva. El original no se toca jamás.\n\n«Análisis»: eliges la columna de fecha, la de cantidad y la de producto, y te decimos cuánta historia tiene cada SKU antes de entrenar con él.\n\n«Reemplazar archivo»: subes la versión de este mes y se mantienen el nombre y el ID, así que los entrenamientos siguen apuntando a la misma fuente.',
      content_title: 'La vista previa: míralas con desconfianza',
      content_body: 'Estas primeras filas son donde se detectan casi todos los problemas, y se detectan a ojo.\n\nQué buscar: fechas que quedaron alineadas como texto en vez de fecha; una fila de totales colada al final; cantidades con símbolo de moneda o separador de miles; celdas vacías donde debería haber un cero; y el mismo producto escrito de dos maneras — cada variante se vuelve un producto distinto y ninguna junta historia suficiente.\n\nSi el archivo es un Excel con varias hojas, arriba salen los botones de hoja: comprueba que la que estamos leyendo es la de ventas.',
      ready_title: 'Cuándo están listos para entrenar',
      ready_body: 'No necesitas datos perfectos. Necesitas cuatro cosas: una fecha legible, la cantidad vendida, un identificador de producto que no cambie de un mes a otro, y suficientes meses seguidos para que se note tu temporada.\n\nCon eso ya puedes pasar a entrenar — es la otra pestaña de arriba, y va a leer estas mismas fuentes sin que tengas que volver a subir nada.',
    },
    en: {
      name: 'How to prepare the data everything depends on',
      intro_title: 'Everything else comes from here',
      intro_body: 'This screen is your data warehouse: the files and connections everything you later read as a purchase recommendation is trained on.\n\nA badly built file almost never throws an error. It gives a credible, wrong forecast, which is far worse. That is why the time you spend here pays better than the time you spend tuning models: it is the one point in the flow where you fix the cause instead of the symptom.',
      new_title: '"New item": file or connection',
      new_body: 'Opens the right-hand panel with two options.\n\n"File upload" accepts CSV and Excel: drop it on the zone, then fill two optional fields. In Name, put something that will still make sense in six months — "Sales 2024–2026", not "export_final(3)". In Description, where it came from and how far it goes: "POS export, through 30/06".\n\n"SQL database" asks for engine, host, port, database, user and password. The real difference: a file is a snapshot of the day you uploaded it and somebody has to replace it; a connection is re-read every time you train.',
      search_title: 'Search sources',
      search_body: 'Filters the left-hand list by name as you type. With three or four files you do not need it; with twenty it is the difference between finding the right one and training on one from six months ago.\n\nWhich is exactly why the name matters: if you search "sales" and get five sources called "sales", the search box cannot save you. Name them by period or origin and this box becomes useful.\n\nThe number above tells you how many sources you have in total, and the refresh icon re-reads the list from the server.',
      item_title: 'The list row, before you trust the file',
      item_body: 'Every row carries the status badge, the size and the row count. It sounds dull and it is the cheapest filter you have.\n\nWhat you are looking for is an inconsistency: a two-year sales file weighing 12 KB is truncated; 300 rows for 200 products is barely one month of history, not a history; and a connection showing red stopped answering and will train on whatever it last managed to read.\n\nCatching it now costs you a minute. Catching it after training costs you a purchasing cycle, because the forecast comes out anyway and it looks reasonable.',
      header_title: 'Rename, test and delete',
      header_body: 'The pencil next to the title renames the source: it changes the label only, not the data, and it is the first thing to fix if you inherited a "data (1).xlsx".\n\nBelow it sit the status badge and the original filename — the one you uploaded, useful when the pretty name no longer resembles it at all.\n\nOn a SQL connection you also get "Test connection": use it before training, not after.\n\nThe bin deletes the source. We ask for confirmation because the trainings made from it are left without their origin.',
      stats_title: 'The four numbers worth a check',
      stats_body: 'Size, rows, columns and type. Read them as a sum that has to match what you think you uploaded.\n\nIf you expected 18 months of sales and see 400 rows, the export was cut short. If you expected 6 columns and there are 40, you uploaded the system\'s full report rather than the sales table — it still works, but the mapping step will cost you more.\n\nAnd an empty or zero "Rows" means we could not read the content: almost always an Excel whose data is not on the first sheet.',
      tabs_title: 'The four tabs and what each is for',
      tabs_body: '"Preview": the first 100 rows exactly as we read them. It is the only way to see what the system sees.\n\n"Edit": fix cells, add or delete rows and columns, give it a name and it is saved as a new source. The original is never touched.\n\n"Analysis": pick the date column, the quantity column and the product column, and we tell you how much history each SKU has before you train on it.\n\n"Replace file": upload this month\'s version and the name and ID stay the same, so existing trainings keep pointing at the same source.',
      content_title: 'The preview: read it with a suspicious eye',
      content_body: 'These first rows are where nearly every problem shows up, and it shows up by eye.\n\nWhat to look for: dates left-aligned as text instead of dates; a totals row slipped in at the bottom; quantities carrying a currency symbol or thousands separator; empty cells where a zero belongs; and the same product spelled two ways — each variant becomes a separate product and neither gathers enough history.\n\nIf the file is an Excel with several sheets, the sheet buttons appear above: check that the one we are reading is the sales one.',
      ready_title: 'When the data is ready to train',
      ready_body: 'You do not need perfect data. You need four things: a readable date, the quantity sold, a product identifier that does not change from one month to the next, and enough consecutive months for your season to show.\n\nWith that you can move on to training — it is the other tab up top, and it will read these same sources without you uploading anything again.',
    },
  },
}
