import type { TourDefinition } from '../types'

export const hoyTour: TourDefinition = {
  id: 'hoy-v3',
  route: '/hoy',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'hoy.freshness', title: 'freshness_title', body: 'freshness_body' },
    { anchor: 'hoy.assumptions', title: 'assumptions_title', body: 'assumptions_body' },
    { anchor: 'hoy.receptions', title: 'receptions_title', body: 'receptions_body' },
    { anchor: 'hoy.kpis', title: 'kpis_title', body: 'kpis_body' },
    { anchor: 'hoy.narrative', title: 'narrative_title', body: 'narrative_body' },
    { anchor: 'hoy.transfers', title: 'transfers_title', body: 'transfers_body' },
    { anchor: 'hoy.actions', title: 'actions_title', body: 'actions_body' },
    { anchor: 'hoy.why', title: 'why_title', body: 'why_body' },
    { anchor: 'hoy.cart', title: 'cart_title', body: 'cart_body' },
  ],
  copy: {
    es: {
      name: 'Cómo usar el panel de compras',
      intro_title: 'Tu día, en una sola pantalla',
      intro_body: 'Esta pantalla responde una pregunta: qué hay que comprar hoy, cuánto y a quién.\n\nEstá ordenada por urgencia real, no alfabéticamente ni por volumen. Lo de arriba es lo que se agota antes. Si sólo tienes cinco minutos al día para esto, empieza arriba y baja hasta que se te acabe el tiempo.',
      freshness_title: 'Qué tan viejos son los datos detrás de esto',
      freshness_body: 'Todo lo que ves se calcula sobre las ventas que subiste la última vez. Si eso fue hace tres semanas, las recomendaciones están razonando sobre un mundo que ya cambió.\n\nPor eso lo decimos aquí arriba en vez de callarlo. Cuando los datos se ponen viejos, degradamos el semáforo y te avisamos en lugar de seguir dando números con la misma confianza.',
      assumptions_title: 'Qué números pusimos nosotros',
      assumptions_body: 'Para recomendarte una compra necesitamos cuatro datos por producto: tiempo de entrega, nivel de servicio, costo unitario y mínimo por pedido.\n\nLo que no nos has dado, lo asumimos — y te decimos exactamente cuánto de la recomendación se apoya en supuestos nuestros antes de que gastes dinero.\n\nEl enlace te lleva a configurarlos ordenados por impacto en plata, no alfabéticamente: primero lo que más cambia tus compras.',
      receptions_title: 'Primero cierra lo que ya pediste',
      receptions_body: 'Aparece arriba a propósito: si un pedido ya llegó y no lo registraste, tu stock real es mayor que el que creemos, y te vamos a recomendar comprar de más.\n\nRegistrar la llegada hace dos cosas: corrige el stock y nos enseña cuánto tarda de verdad ese proveedor. Con unas cuantas recepciones dejamos de usar el tiempo de entrega que configuraste y empezamos a usar el real.',
      kpis_title: 'Los cuatro números de arriba',
      kpis_body: 'SKUs monitoreados: cuántos productos vigilamos con predicción y stock.\n\nRiesgo hoy: se agotan antes de que llegue un pedido nuevo. Esos no pueden esperar a mañana.\n\nEsta semana: aún tienes margen, pero entran en la compra de esta semana.\n\nPrecisión promedio: qué tan bien acertó el modelo contra tu propio historial, en trozos que no vio al entrenar. No es una promesa sobre el futuro; es el historial de aciertos con el que decides cuánto fiarte.',
      narrative_title: 'El resumen del día en palabras',
      narrative_body: 'La misma información de la pantalla, redactada. Sirve para dos cosas: revisarla de un vistazo antes de entrar al detalle, y reenviarla a alguien que no va a abrir la app.\n\nSale de tus datos, no de una opinión: cada cifra que menciona está en la pantalla.',
      transfers_title: 'Antes de comprar, mira si ya lo tienes',
      transfers_body: 'Si manejas más de una bodega, a veces el producto que falta en una sobra en otra. Mover es más rápido y más barato que comprar.\n\nPor eso esto va antes que las compras: cada transferencia que aceptas es una compra que no haces. Te decimos cuántos días de cobertura le quedan a la bodega que dona, para que resolver un problema no cree otro.',
      actions_title: 'Cada tarjeta es una decisión',
      actions_body: 'Aprobar, rechazar, o cambiar la cantidad antes de aprobar. La cantidad sugerida es un punto de partida, no una orden: tú conoces cosas que tus datos no dicen.\n\nRechazar también sirve para algo. Con el tiempo, cuánto sigues y cuánto descartas nos dice si los tiempos de entrega y niveles de servicio están bien puestos.',
      why_title: 'Siempre puedes preguntar por qué',
      why_body: 'Te abrimos el cálculo entero: cuánto stock te queda, cuánto vendes al día, cuánto tarda el proveedor, y de dónde salió cada uno de esos números.\n\nSi un valor lo asumimos nosotros en vez de recibirlo de ti, lo marcamos. Nunca deberías aprobar una compra por confiar en una caja negra — y menos si parte de la caja la rellenamos nosotros.',
      cart_title: 'Lo aprobado se junta abajo',
      cart_body: 'A medida que apruebas, la barra de abajo acumula el total que vas a comprometer, y cuánto margen protege ese pedido si tienes precios cargados.\n\nDe ahí sale la orden de compra: se genera agrupada por proveedor y puedes enviarla o descargarla. Hasta que la generes, nada ha salido de la app.',
    },
    en: {
      name: 'How to use the purchasing panel',
      intro_title: 'Your day, on one screen',
      intro_body: 'This screen answers one question: what has to be bought today, how much, and from whom.\n\nIt is ordered by real urgency, not alphabetically or by volume. What is at the top runs out first. If you only have five minutes a day for this, start at the top and work down until the time runs out.',
      freshness_title: 'How old the data behind this is',
      freshness_body: 'Everything you see is computed on the sales you last uploaded. If that was three weeks ago, these recommendations are reasoning about a world that has moved on.\n\nThat is why we say it up here instead of keeping quiet. When data goes stale we degrade the stock signal and tell you, rather than keep quoting numbers with the same confidence.',
      assumptions_title: 'Which numbers are ours',
      assumptions_body: 'To recommend a purchase we need four things per product: lead time, service level, unit cost and minimum order quantity.\n\nWhatever you have not given us, we assume — and we tell you exactly how much of the recommendation rests on our guesses before you spend money.\n\nThe link takes you to configure them ranked by money impact, not alphabetically: what changes your purchasing most comes first.',
      receptions_title: 'Close what you already ordered first',
      receptions_body: 'This sits at the top on purpose: if an order arrived and you did not record it, your real stock is higher than we think, and we will recommend buying too much.\n\nRecording an arrival does two things: it corrects the stock and it teaches us how long that supplier really takes. After a few receptions we stop using the lead time you configured and start using the real one.',
      kpis_title: 'The four numbers at the top',
      kpis_body: 'Monitored SKUs: how many products we watch with both a forecast and stock.\n\nAt risk today: they run out before a new order could arrive. Those cannot wait until tomorrow.\n\nThis week: still some room, but they belong in this week\'s purchase.\n\nAverage accuracy: how well the model did against your own history, on slices it never saw while training. It is not a promise about the future; it is the track record you use to decide how much to trust it.',
      narrative_title: 'The day in words',
      narrative_body: 'The same information as the screen, written out. Useful for two things: skimming before you go into the detail, and forwarding to someone who will not open the app.\n\nIt comes from your data, not from an opinion: every figure it mentions is on the screen.',
      transfers_title: 'Before buying, check whether you already have it',
      transfers_body: 'With more than one warehouse, the product missing in one is sometimes sitting spare in another. Moving is faster and cheaper than buying.\n\nThat is why this comes before the purchases: every transfer you accept is a purchase you do not make. We tell you how many days of coverage the donating warehouse keeps, so solving one problem does not create another.',
      actions_title: 'Every card is one decision',
      actions_body: 'Approve, reject, or change the quantity before approving. The suggested quantity is a starting point, not an order: you know things your data does not say.\n\nRejecting is useful too. Over time, how much you follow versus discard tells us whether the lead times and service levels are set right.',
      why_title: 'You can always ask why',
      why_body: 'We open up the whole calculation: how much stock is left, how much you sell per day, how long the supplier takes, and where each of those numbers came from.\n\nIf a value was assumed by us rather than given by you, we mark it. You should never approve a purchase because you trust a black box — least of all one we partly filled in.',
      cart_title: 'What you approve collects below',
      cart_body: 'As you approve, the bar at the bottom accumulates the total you are about to commit, and how much margin that order protects if you have prices loaded.\n\nThe purchase order comes from there: generated grouped by supplier, ready to send or download. Until you generate it, nothing has left the app.',
    },
  },
}
