import type { TourDefinition } from '../types'

export const hoyTour: TourDefinition = {
  id: 'hoy-v4',
  route: '/compras',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'hoy.freshness', title: 'freshness_title', body: 'freshness_body' },
    { anchor: 'hoy.assumptions', title: 'assumptions_title', body: 'assumptions_body' },
    { anchor: 'hoy.receptions', title: 'receptions_title', body: 'receptions_body' },
    { anchor: 'hoy.receive', title: 'receive_title', body: 'receive_body' },
    { anchor: 'hoy.kpis', title: 'kpis_title', body: 'kpis_body' },
    { anchor: 'hoy.narrative', title: 'narrative_title', body: 'narrative_body' },
    { anchor: 'hoy.transfers', title: 'transfers_title', body: 'transfers_body' },
    { anchor: 'hoy.actions', title: 'actions_title', body: 'actions_body' },
    { anchor: 'hoy.why', title: 'why_title', body: 'why_body' },
    { anchor: 'hoy.supplier', title: 'supplier_title', body: 'supplier_body' },
    { anchor: 'hoy.qty', title: 'qty_title', body: 'qty_body' },
    { anchor: 'hoy.decide', title: 'decide_title', body: 'decide_body' },
    { anchor: 'hoy.cart', title: 'cart_title', body: 'cart_body' },
    { anchor: 'hoy.cart_warehouse', title: 'destination_title', body: 'destination_body' },
    { anchor: 'hoy.download', title: 'download_title', body: 'download_body' },
  ],
  copy: {
    es: {
      name: 'Cómo usar el panel de compras',
      intro_title: 'Tu día, en una sola pantalla',
      intro_body: 'Esta pantalla responde una pregunta: qué hay que comprar hoy, cuánto y a quién.\n\nEstá ordenada por urgencia real, no alfabéticamente ni por volumen. Lo de arriba es lo que se agota antes. Si sólo tienes cinco minutos al día para esto, empieza arriba y baja hasta que se te acabe el tiempo.',
      freshness_title: 'Qué tan viejos son los datos detrás de esto',
      freshness_body: 'Todo lo que ves se calcula sobre las ventas que subiste la última vez. Si eso fue hace tres semanas, las recomendaciones están razonando sobre un mundo que ya cambió.\n\nPor eso lo decimos aquí arriba en vez de callarlo. Cuando los datos se ponen viejos, degradamos el semáforo y te avisamos en lugar de seguir dando números con la misma confianza.',
      assumptions_title: 'Qué números pusimos nosotros',
      assumptions_body: 'Para recomendarte una compra necesitamos cuatro datos por producto: tiempo de entrega, nivel de servicio, costo unitario y mínimo por pedido.\n\nLo que no nos has dado, lo asumimos — y te decimos exactamente cuánto de la recomendación se apoya en supuestos nuestros antes de que gastes dinero.\n\nEl enlace te lleva a configurarlos ordenados por impacto en plata, no alfabéticamente: primero lo que más cambia tus compras.',
      receptions_title: 'Primero cierra lo que ya pediste',
      receptions_body: 'Esta franja roja lista los pedidos que ya deberían haber llegado según lo que tarda ese proveedor, y nadie marcó como recibidos.\n\nAparece arriba a propósito: si un pedido llegó y no lo registraste, tu stock real es mayor que el que creemos, y te vamos a recomendar comprar de más.\n\nDos salidas válidas: si ya llegó, regístralo con el botón de la derecha; si de verdad viene atrasado, llama al proveedor. Lo que no sirve es dejarlo ahí una semana más.',
      receive_title: 'El botón «Registrar llegada»',
      receive_body: 'Abre la ventana de recepción de ese pedido sin que tengas que ir a Pedidos.\n\nAdentro anotas cuánto llegó de cada producto. Si pediste 100 y bajaron 60 cajas, escribe 60: el pedido queda parcial y las 40 que faltan siguen contando como que vienen en camino.\n\nRegistrar hace dos cosas: corrige tu stock y mide cuánto tardó de verdad ese proveedor. Con unas cuantas recepciones dejamos de usar el tiempo de entrega que configuraste y empezamos a usar el real.',
      kpis_title: 'Los cinco números de arriba',
      kpis_body: 'SKUs monitoreados: productos con predicción y stock a la vez. Riesgo hoy: se agotan antes de que llegue un pedido que hagas hoy. Esta semana: aguantan, pero entran en la compra de esta semana.\n\nPrecisión promedio: cuánto acertó el modelo contra tu propio historial. Arriba de 80% es sólido; abajo de 60%, revisa tus datos antes de fiarte de las cantidades.\n\nValor de inventario: la plata parada en bodega, sólo de los productos con costo cargado.',
      narrative_title: 'El resumen del día en palabras',
      narrative_body: 'La misma información de la pantalla, redactada. Sirve para dos cosas: revisarla de un vistazo antes de entrar al detalle, y reenviarla a alguien que no va a abrir la app.\n\nSale de tus datos, no de una opinión: cada cifra que menciona está en la pantalla.',
      transfers_title: 'Antes de comprar, mira si ya lo tienes',
      transfers_body: 'Si manejas más de una bodega, a veces el producto que falta en una sobra en otra. Mover es más rápido y más barato que comprar.\n\nCada sugerencia dice cuánto mover, desde qué bodega y cuánta cobertura le queda a la que dona. Si la que dona se queda con 3 días, no la aceptes: resolver un problema no debe crear otro.\n\n«Crear transferencia» deja el traslado en tránsito. El stock recién cuenta en la bodega destino cuando registras su llegada en Pedidos → Transferencias.',
      actions_title: 'Cada tarjeta es una decisión',
      actions_body: 'Una tarjeta por producto que hay que comprar. Arriba: el nombre, el semáforo y en una línea por qué aparece («te quedan 5 días de stock y tu proveedor tarda 7»). Abajo: la cantidad, el valor estimado y los dos botones.\n\nPrimero el bloque urgente, después el de esta semana, y dentro de cada uno por urgencia.\n\nNada de lo que hagas en una tarjeta compra ni envía nada por sí solo: todo se acumula en la barra verde de abajo y sale de la app en un único paso, al final.',
      why_title: 'Siempre puedes preguntar por qué',
      why_body: 'Abre el cálculo entero de esa tarjeta: cobertura que te queda, cuánto vendes al día, tiempo de entrega, nivel de servicio, costo unitario, mínimo por pedido, stock actual y punto de reorden.\n\nCada valor lleva su origen. «Tuyo» es un dato que cargaste, «aprendido» lo medimos de tus recepciones, «supuesto» lo pusimos nosotros porque nadie lo dio.\n\nRegla práctica: si la cantidad te parece rara y el costo o el tiempo de entrega dicen «supuesto», arregla el dato en Inventario en vez de corregir la cantidad a mano todos los días.',
      supplier_title: 'A quién se le va a pedir',
      supplier_body: 'Sale de la ficha del producto, pero aquí lo cambias antes de aprobar: si tu proveedor de siempre está sin existencias o te cotizó caro, elige otro y esa línea viaja en la orden del nuevo.\n\nLa orden de compra se agrupa por este campo. Si lo dejas en «Sin proveedor», la línea sale en un bloque suelto que después tienes que asignar a mano, y no se puede enviar por correo ni WhatsApp porque no hay a quién mandársela.',
      qty_title: 'La cantidad se edita',
      qty_body: 'Haz clic en el número, escribe y Enter. Ya cubre lo que vendes mientras el pedido viaja, más un colchón, y está redondeada al mínimo del proveedor.\n\nCámbiala si sabes algo que los datos no dicen: una promoción, dos semanas cerrado, cajas de 12. No la muevas «por si acaso»: de 400 a 1.000 es plata parada, y bajarla a la mitad es quebrar stock mientras el pedido viene en camino.',
      decide_title: 'Aprobar y rechazar',
      decide_body: 'Aprobar mete la línea al carrito de abajo con la cantidad y el proveedor de la tarjeta: no compra ni manda nada, sólo la deja lista, y puedes deshacerlo.\n\nRechazar la saca del día — ya lo pediste por fuera, vas a descontinuarlo, el proveedor no tiene. No es «más tarde»: sólo vuelve en el próximo cálculo.',
      cart_title: 'Lo aprobado se junta abajo',
      cart_body: 'A medida que apruebas, la barra verde acumula cuántos productos llevas, el total que vas a comprometer y, si tienes precios cargados, cuánta venta y cuánto margen protege ese pedido.\n\nCuando sólo algunos productos tienen precio te lo decimos: el total en plata siempre está completo, el margen no.\n\n«Limpiar» vacía el carrito de una vez. No rechaza nada: las tarjetas vuelven a quedar pendientes, listas para decidirlas de nuevo.',
      destination_title: 'A qué bodega entra',
      destination_body: 'Sólo aparece si manejas más de una bodega: dice dónde va a entrar la mercadería de esta compra.\n\nSe aplica a la orden entera, no línea por línea. Si estás surtiendo la sucursal, cámbialo antes de generar; si lo dejas en la bodega principal, el producto va a sumar stock donde no estaba el problema y la sucursal va a seguir en rojo mañana.\n\nPara repartir la misma compra entre dos bodegas, genera dos órdenes: aprueba unas líneas, genera con una bodega, y repite con el resto.',
      download_title: 'Generar la orden',
      download_body: 'Este botón convierte el carrito en una orden real: la registra en Pedidos, la agrupa por proveedor y te descarga el archivo.\n\nGenerar no es enviar. En cuanto se genera te ofrecemos mandarla por correo o WhatsApp a cada proveedor; hasta que lo hagas, el proveedor no sabe nada.\n\nRevisa dos cosas antes de tocarlo: que ninguna línea haya quedado sin proveedor y que el total sea el que estás dispuesto a comprometer. Ya generada, la orden vive en Pedidos y es la que después vas a marcar como recibida.',
    },
    en: {
      name: 'How to use the purchasing panel',
      intro_title: 'Your day, on one screen',
      intro_body: 'This screen answers one question: what has to be bought today, how much, and from whom.\n\nIt is ordered by real urgency, not alphabetically or by volume. What is at the top runs out first. If you only have five minutes a day for this, start at the top and work down until the time runs out.',
      freshness_title: 'How old the data behind this is',
      freshness_body: 'Everything you see is computed on the sales you last uploaded. If that was three weeks ago, these recommendations are reasoning about a world that has moved on.\n\nThat is why we say it up here instead of keeping quiet. When data goes stale we degrade the stock signal and tell you, rather than keep quoting numbers with the same confidence.',
      assumptions_title: 'Which numbers are ours',
      assumptions_body: 'To recommend a purchase we need four things per product: lead time, service level, unit cost and minimum order quantity.\n\nWhatever you have not given us, we assume — and we tell you exactly how much of the recommendation rests on our guesses before you spend money.\n\nThe link takes you to configure them ranked by money impact, not alphabetically: what changes your purchasing most comes first.',
      receptions_title: 'Close what you already ordered first',
      receptions_body: 'This red strip lists the orders that should already have arrived, going by how long that supplier takes, and that nobody marked as received.\n\nIt sits at the top on purpose: if an order arrived and you did not record it, your real stock is higher than we think, and we will recommend buying too much.\n\nTwo valid ways out: if it did arrive, record it with the button on the right; if it is genuinely late, call the supplier. What does not help is leaving it there another week.',
      receive_title: 'The "Record arrival" button',
      receive_body: 'It opens the reception window for that order without making you go to Orders.\n\nInside you write down how much of each product arrived. If you ordered 100 and 60 boxes came off the truck, put 60: the order stays partial and the missing 40 keep counting as still in transit.\n\nRecording does two things: it corrects your stock and it measures how long that supplier really took. After a few receptions we stop using the lead time you configured and start using the real one.',
      kpis_title: 'The five numbers at the top',
      kpis_body: 'Monitored SKUs: products with both a forecast and stock. At risk today: they run out before an order placed today could arrive. This week: they hold, but they belong in this week\'s purchase.\n\nAverage accuracy: how well the model did against your own history. Above 80% is solid; below 60%, review your data before trusting the quantities.\n\nInventory value: the money sitting idle in the warehouse, only from products that have a cost loaded.',
      narrative_title: 'The day in words',
      narrative_body: 'The same information as the screen, written out. Useful for two things: skimming before you go into the detail, and forwarding to someone who will not open the app.\n\nIt comes from your data, not from an opinion: every figure it mentions is on the screen.',
      transfers_title: 'Before buying, check whether you already have it',
      transfers_body: 'With more than one warehouse, the product missing in one is sometimes sitting spare in another. Moving is faster and cheaper than buying.\n\nEach suggestion says how much to move, from which warehouse, and how much coverage the donating one keeps. If the donor is left with 3 days, do not accept it: solving one problem must not create another.\n\n"Create transfer" puts the move in transit. The stock only counts in the destination warehouse once you record its arrival under Orders → Transfers.',
      actions_title: 'Every card is one decision',
      actions_body: 'One card per product that has to be bought. At the top: the name, the stock signal, and one line saying why it is here ("you have 5 days of stock left and your supplier takes 7"). At the bottom: the quantity, the estimated value and the two buttons.\n\nThe urgent block comes first, this week\'s block after it, and inside each one they are sorted by urgency.\n\nNothing you do on a card buys or sends anything by itself: it all collects in the green bar at the bottom and leaves the app in a single step, at the end.',
      why_title: 'You can always ask why',
      why_body: 'It opens the whole calculation behind that card: coverage left, how much you sell per day, lead time, service level, unit cost, minimum order quantity, current stock and reorder point.\n\nEvery value carries its origin. "Yours" is data you loaded, "learned" we measured from your receptions, "assumed" we filled in because nobody gave it.\n\nRule of thumb: if the quantity looks odd and the cost or the lead time says "assumed", fix the data in Inventory instead of correcting the quantity by hand every day.',
      supplier_title: 'Who this line gets ordered from',
      supplier_body: 'It comes from the product record, but you change it here before approving: if your usual supplier is out of stock or quoted you high, pick another and that line travels in the new one\'s order.\n\nThe purchase order is grouped by this field. Left on "No supplier", the line comes out in a loose block you have to assign by hand later, and it cannot be sent by email or WhatsApp because there is nobody to send it to.',
      qty_title: 'The quantity is editable',
      qty_body: 'Click the number, type, Enter. It already covers what you sell while the order is in transit, plus a buffer, and it is rounded up to the supplier\'s minimum.\n\nChange it if you know something the data does not: a promotion, two weeks closed, cases of 12. Do not move it "just in case": 400 to 1,000 is idle money, and halving it means running out while the order is on its way.',
      decide_title: 'Approve and reject',
      decide_body: 'Approve puts the line in the cart below with the card\'s quantity and supplier: it buys nothing and sends nothing, it only gets it ready, and you can undo it.\n\nReject takes it out of the day — you already ordered it outside, you are discontinuing it, the supplier has none. Not "later": it only returns at the next calculation.',
      cart_title: 'What you approve collects below',
      cart_body: 'As you approve, the green bar accumulates how many products you have, the total you are about to commit and — if you have prices loaded — how much sales and margin that order protects.\n\nWhen only some products have a price we say so: the money total is always complete, the margin is not.\n\n"Clear" empties the cart in one go. It rejects nothing: the cards go back to pending, ready to be decided again.',
      destination_title: 'Which warehouse it goes into',
      destination_body: 'It only appears if you run more than one warehouse: it says where the goods from this purchase will land.\n\nIt applies to the whole order, not line by line. If you are restocking the branch, change it before generating; leave it on the main warehouse and the goods will add stock where the problem was not, while the branch stays in the red tomorrow.\n\nTo split one purchase across two warehouses, generate two orders: approve some lines, generate with one warehouse, then repeat with the rest.',
      download_title: 'Generating the order',
      download_body: 'This button turns the cart into a real order: it records it under Orders, groups it by supplier and downloads the file.\n\nGenerating is not sending. As soon as it is generated we offer to send it by email or WhatsApp to each supplier; until you do, the supplier knows nothing.\n\nCheck two things before pressing it: that no line was left without a supplier, and that the total is the one you are willing to commit. Once generated, the order lives under Orders and is the one you will later mark as received.',
    },
  },
}
