import type { TourDefinition } from '../types'

export const inventoryTour: TourDefinition = {
  id: 'inventory-v4',
  route: '/inventario',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'inv.views', title: 'views_title', body: 'views_body' },
    { anchor: 'inv.filters', title: 'filters_title', body: 'filters_body' },
    { anchor: 'inv.search', title: 'search_title', body: 'search_body' },
    { anchor: 'inv.signal', title: 'signal_title', body: 'signal_body' },
    { anchor: 'inv.coverage', title: 'coverage_title', body: 'coverage_body' },
    { anchor: 'inv.suggest', title: 'suggest_title', body: 'suggest_body' },
    { anchor: 'inv.leadtime', title: 'leadtime_title', body: 'leadtime_body' },
    { anchor: 'inv.expand', title: 'expand_title', body: 'expand_body' },
    { anchor: 'inv.simulate', title: 'simulate_title', body: 'simulate_body' },
    { anchor: 'inv.edit', title: 'edit_title', body: 'edit_body' },
    { anchor: 'inv.update_stock', title: 'stock_title', body: 'stock_body' },
    { anchor: 'inv.update_lead', title: 'lead_field_title', body: 'lead_field_body' },
    { anchor: 'inv.save', title: 'save_title', body: 'save_body' },
    { anchor: 'inv.export', title: 'export_title', body: 'export_body' },
    { title: 'config_title', body: 'config_body' },
  ],
  copy: {
    es: {
      name: 'Cómo leer el semáforo',
      intro_title: 'Tu catálogo entero, con el detalle completo',
      intro_body: 'El Panel de Compras te da las decisiones del día. Esta pantalla te da todo: cada producto, su cálculo y sus parámetros, para revisar y ajustar.\n\nAquí es donde se corrige la causa cuando una recomendación no te cuadra.',
      views_title: 'Cinco formas de ver lo mismo',
      views_body: 'Tabla: todo el detalle, columna por columna, con el cálculo y la edición de cada fila. Es la vista para analizar.\n\nSimple: producto, semáforo, cantidad y proveedor. Para revisar rápido sin distraerte.\n\nProveedor: agrupado por quién te vende. Es la vista para preparar una compra, porque los pedidos se hacen por proveedor, no por producto suelto.\n\nActualizar stock: una planilla para corregir stock y tiempos de entrega de muchos productos seguidos.\n\nInmovilizado: lo que lleva meses sin moverse. Plata dormida, no compras.',
      filters_title: 'Las tarjetas de arriba también filtran',
      filters_body: 'No son sólo un conteo: haz clic en una y la tabla de abajo se queda con esos productos. Clic otra vez y vuelve todo.\n\n«Pedir ya» es la que usarás casi siempre: te deja en pantalla exactamente lo que hay que resolver hoy. «Sobrestock» sirve para la conversación contraria, qué dejar de comprar.\n\nEl filtro se combina con la búsqueda, así que «Pedir ya» más escribir «leche» te da los lácteos en rojo y nada más. Si la tabla aparece vacía y no entiendes por qué, casi siempre es un filtro que quedó puesto.',
      search_title: 'Buscar un producto concreto',
      search_body: 'Busca por código, por nombre y por proveedor, sin importar mayúsculas: escribe «1201», «leche» o «Distribuidora» y la tabla se reduce mientras tecleas.\n\nEs para el caso más común del día: alguien pregunta por un producto y quieres ver su stock y su cobertura sin recorrer 800 filas.\n\nLa X limpia la búsqueda y el contador de la derecha te dice cuántos SKUs quedaron. Ojo: la búsqueda filtra sólo lo que la sesión cargó; un producto que nunca subiste no aparece por más que lo escribas.',
      signal_title: 'El semáforo: cuatro estados y qué hacer con cada uno',
      signal_body: 'Pedir YA: se agota antes de que llegue un pedido que hagas hoy. Ya vas tarde.\n\nPedir pronto: alcanza, pero entra en la compra de esta semana.\n\nOK: cubierto, no requiere nada.\n\nSobrestock: tienes mucho más de lo que vas a vender. No es un error, es dinero parado — y a veces producto que va a caducar.\n\nLos colores están calibrados para que se distingan también con daltonismo, y nunca son la única señal: siempre hay texto.',
      coverage_title: 'Cobertura: el número que manda',
      coverage_body: 'Cuántos días (o semanas, o meses) te dura el stock actual al ritmo al que vendes.\n\nEl semáforo sale de comparar esa cobertura contra el tiempo de entrega del proveedor. Ahí está toda la lógica: si te quedan 5 días de stock y tu proveedor tarda 7, ya estás en problemas aunque la bodega se vea llena.',
      suggest_title: 'De dónde sale la cantidad sugerida',
      suggest_body: 'Cubre dos cosas: lo que vas a vender mientras el pedido viaja, más un colchón por si vendes más de lo previsto.\n\nEl tamaño del colchón lo decide tu nivel de servicio. Al 95% aceptas quedarte corto 1 de cada 20 veces; al 99% casi nunca, pero pagas mucho más inventario por esa tranquilidad.\n\nAl final redondeamos hacia arriba al mínimo que te exige el proveedor, porque pedir menos que su mínimo no es una opción real.\n\nEl número está subrayado: puedes editarlo aquí mismo si vas a exportar la orden desde esta pantalla.',
      leadtime_title: 'El tiempo de entrega, y por qué lo aprendemos',
      leadtime_body: 'Es el dato que más mueve tus compras: entra en el cálculo dos veces, en lo que consumes esperando y en el tamaño del colchón.\n\nPor eso no nos quedamos con el que configuraste. Cada vez que registras una llegada medimos lo que tardó de verdad, y tras unas cuantas empezamos a usar ese número.\n\nCuando el valor es aprendido te lo indicamos, para que sepas cuándo el sistema ya sabe más que la ficha.',
      expand_title: 'Abre el cálculo de cualquier fila',
      expand_body: 'Esta flecha despliega la explicación completa de ese producto: la fórmula con tus números puestos — demanda diaria por tiempo de entrega, más stock de seguridad, menos lo que ya tienes — y de dónde salió cada parámetro.\n\nEs la forma de contestar «¿por qué me pide 700 unidades de esto?» sin tener que creernos.\n\nSi al abrirla ves que la demanda diaria no se parece a lo que vendes, el problema no es la fórmula: son las ventas que se subieron.',
      simulate_title: 'El simulador: «¿y si…?» sin tocar nada',
      simulate_body: 'Los deslizadores abren la misma fila con tres perillas: tiempo de entrega, variación de demanda y stock extra. Abajo ves la cantidad sugerida nueva al lado de la original.\n\nÚsalo antes de negociar. Subir el tiempo de entrega de 7 a 21 días te muestra en unidades lo que cuesta un proveedor lento. Poner la demanda en 150% es la pregunta de temporada: «si diciembre vende la mitad más, ¿cuánto tengo que traer?».\n\nNo guarda nada ni cambia tus datos: es una calculadora. Para que el cambio sea de verdad, edita la fila o la ficha del proveedor.',
      edit_title: 'El lápiz: los datos que mandan en el cálculo',
      edit_body: 'Abre la fila para editarla. Nombre, categoría y marca son etiquetas; los que mueven la compra son estos:\n\nStock actual: lo que hay hoy en bodega, contado.\n\nTiempo de entrega: días reales desde que pides hasta que descargas.\n\nMínimo por pedido: si el proveedor vende por caja de 24, pon 24 y nunca te sugeriremos 10.\n\nCosto: sin él no hay total de la orden ni valor de inventario. Precio de venta: sin él no podemos mostrarte el margen que proteges.\n\nNivel de servicio: 95% para casi todo; 99% sólo donde quebrar stock te cuesta el cliente.',
      stock_title: 'Stock actual, producto por producto',
      stock_body: 'La vista Actualizar es una planilla para corregir muchos productos seguidos: escribe, Enter guarda la fila y salta a la de abajo, Esc deshace esa fila.\n\nEn esta columna va lo que hay físicamente hoy: si contaste 340, pon 340. No pongas lo que «debería» haber, ni le sumes lo que viene en camino — los pedidos en tránsito ya los contamos aparte, y sumarlos aquí hace que dejemos de pedir justo antes de que te quedes sin producto.\n\nUn producto sin stock cargado queda fuera del semáforo: no aparece en rojo, simplemente no se recomienda.',
      lead_field_title: 'Tiempo de entrega y proveedor',
      lead_field_body: 'Días desde que mandas el pedido hasta que la mercadería está en tu bodega. Es calendario, no días hábiles, e incluye lo que el proveedor tarda en despachar.\n\nUn valor sano para un proveedor local anda entre 3 y 10; una importación se va a 30, 45 o más. Si lo pones corto — 5 donde de verdad tarda 15 — vamos a recomendar tarde y vas a quebrar stock sin entender por qué. Si lo pones largo de más, compras de más y antes de tiempo.\n\nAl lado va el proveedor. Escríbelo siempre igual: la orden de compra se agrupa exactamente por ese texto.',
      save_title: 'Guardar los cambios',
      save_body: 'El punto ámbar marca las filas que tocaste y el botón te dice cuántas van. Nada se guarda solo: si sales de la pantalla con cambios pendientes, se pierden.\n\nGuardar reescribe el stock y los tiempos de entrega de esas filas y recalcula el semáforo con los valores nuevos. Es normal que varias filas cambien de color al terminar.\n\n«Descartar» devuelve la planilla a como estaba antes de que empezaras a escribir; no deshace lo que ya guardaste. Si vas a cargar cientos de filas, usa el CSV en vez de teclear.',
      export_title: 'Sacar y meter datos',
      export_body: 'CSV sube un archivo con sku, current_stock y lead_time_days: la forma rápida de cargar 500 productos de una vez. Plantilla te descarga ese mismo archivo con las columnas ya puestas, y es por donde conviene empezar.\n\n«Exportar OC» baja la compra sugerida tal como está; «Exportar OC (editada)» baja las cantidades que corregiste a mano; PDF arma el documento para mandárselo al proveedor.\n\nLa orden se genera agrupada por proveedor y queda registrada en Pedidos, para que después registres la llegada y cierres el ciclo.',
      config_title: 'Mientras mejor configurado, mejor compra',
      config_body: 'Tiempo de entrega, costo, mínimo por pedido y nivel de servicio de cada producto o proveedor. Lo que no nos des, lo asumimos — y siempre te lo marcamos como supuesto.\n\nNo hace falta configurarlo todo de golpe. Empieza por los productos que más plata mueven; el resto puede esperar, y la app te los ordena por ese criterio.',
    },
    en: {
      name: 'How to read the stock signal',
      intro_title: 'Your whole catalogue, in full detail',
      intro_body: 'The purchasing panel gives you the day\'s decisions. This screen gives you everything: every product, its calculation and its parameters, to review and adjust.\n\nThis is where you fix the cause when a recommendation does not look right.',
      views_title: 'Five ways to see the same thing',
      views_body: 'Table: full detail, column by column, with each row\'s calculation and editing. The view for analysing.\n\nSimple: product, signal, quantity and supplier. For a fast review without distraction.\n\nSupplier: grouped by who sells it to you. The view for preparing a purchase, because orders are placed per supplier, not per loose product.\n\nUpdate stock: a spreadsheet for correcting stock and lead times across many products in a row.\n\nDead stock: what has not moved in months. Sleeping money, not purchases.',
      filters_title: 'The cards at the top are filters too',
      filters_body: 'They are not just a count: click one and the table below keeps only those products. Click again and everything comes back.\n\n"Order now" is the one you will use most: it leaves exactly what has to be solved today on screen. "Overstock" is for the opposite conversation, what to stop buying.\n\nThe filter combines with the search, so "Order now" plus typing "milk" gives you the dairy in the red and nothing else. If the table looks empty and you cannot see why, it is almost always a filter left on.',
      search_title: 'Finding one product',
      search_body: 'It searches by code, by name and by supplier, ignoring case: type "1201", "milk" or "Distributor" and the table narrows as you type.\n\nIt is for the most common moment of the day: someone asks about a product and you want its stock and coverage without scrolling 800 rows.\n\nThe X clears the search and the counter on the right says how many SKUs are left. Note it only filters what the session loaded: a product you never uploaded will not appear no matter how you spell it.',
      signal_title: 'The signal: four states and what to do with each',
      signal_body: 'Order now: runs out before an order placed today could arrive. You are already late.\n\nOrder soon: it holds, but it belongs in this week\'s purchase.\n\nOK: covered, needs nothing.\n\nOverstock: far more than you will sell. Not an error — idle money, and sometimes product that will expire.\n\nThe colours are calibrated to stay distinguishable with colour blindness, and are never the only signal: there is always text.',
      coverage_title: 'Coverage: the number that drives everything',
      coverage_body: 'How many days (or weeks, or months) your current stock lasts at the rate you are selling.\n\nThe signal comes from comparing that coverage against the supplier\'s lead time. That is the whole logic: if you have 5 days of stock and your supplier takes 7, you are already in trouble no matter how full the warehouse looks.',
      suggest_title: 'Where the suggested quantity comes from',
      suggest_body: 'It covers two things: what you will sell while the order is in transit, plus a buffer in case you sell more than forecast.\n\nThe size of that buffer is set by your service level. At 95% you accept running short 1 time in 20; at 99% almost never, but you pay for it in far more inventory.\n\nFinally we round up to your supplier\'s minimum, because ordering less than their minimum is not a real option.\n\nThe number is underlined: you can edit it right here if you are exporting the order from this screen.',
      leadtime_title: 'Lead time, and why we learn it',
      leadtime_body: 'It is the single input that moves your purchasing most: it enters the calculation twice, in what you consume while waiting and in the size of the buffer.\n\nSo we do not settle for the one you configured. Every time you record an arrival we measure what it actually took, and after a few we start using that number instead.\n\nWhen a value is learned we say so, so you know when the system already knows more than the record does.',
      expand_title: 'Open the calculation on any row',
      expand_body: 'This arrow unfolds the full explanation for that product: the formula with your numbers in it — daily demand times lead time, plus safety stock, minus what you already hold — and where each parameter came from.\n\nIt is how you answer "why is it asking me for 700 units of this?" without having to take our word for it.\n\nIf you open it and the daily demand does not look like what you actually sell, the problem is not the formula: it is the sales that were uploaded.',
      simulate_title: 'The simulator: "what if…?" without touching anything',
      simulate_body: 'The sliders open the same row with three knobs: lead time, demand variation and extra stock. Below, the new suggested quantity sits next to the original.\n\nUse it before negotiating. Pushing the lead time from 7 to 21 days shows you in units what a slow supplier costs. Setting demand to 150% is the seasonal question: "if December sells half as much again, how much do I have to bring in?".\n\nIt saves nothing and changes no data: it is a calculator. To make the change real, edit the row or the supplier record.',
      edit_title: 'The pencil: the data that drives the calculation',
      edit_body: 'It opens the row for editing. Name, category and brand are labels; these are the ones that move the purchase:\n\nCurrent stock: what is in the warehouse today, counted.\n\nLead time: real days from ordering to unloading.\n\nMinimum order: if the supplier sells by the case of 24, put 24 and we will never suggest 10.\n\nCost: without it there is no order total and no inventory value. Sale price: without it we cannot show you the margin you are protecting.\n\nService level: 95% for almost everything; 99% only where a stockout costs you the customer.',
      stock_title: 'Current stock, product by product',
      stock_body: 'The Update view is a spreadsheet for correcting many products in a row: type, Enter saves the row and jumps to the next, Esc undoes that row.\n\nThis column takes what is physically there today: if you counted 340, put 340. Do not put what "should" be there, and do not add what is on its way — orders in transit are already counted separately, and adding them here makes us stop ordering right before you run out.\n\nA product with no stock loaded stays out of the signal: it does not show red, it simply gets no recommendation.',
      lead_field_title: 'Lead time and supplier',
      lead_field_body: 'Days from sending the order to the goods being in your warehouse. Calendar days, not working days, including how long the supplier takes to dispatch.\n\nA sane value for a local supplier is 3 to 10; an import goes to 30, 45 or more. Set it short — 5 where it really takes 15 — and we will recommend late and you will run out without understanding why. Set it too long and you buy too much, too early.\n\nNext to it is the supplier. Always spell it the same way: the purchase order is grouped by exactly that text.',
      save_title: 'Saving the changes',
      save_body: 'The amber dot marks the rows you touched and the button says how many there are. Nothing saves by itself: leave the screen with pending changes and they are gone.\n\nSaving rewrites the stock and lead times of those rows and recomputes the signal with the new values. It is normal for several rows to change colour when it finishes.\n\n"Discard" returns the sheet to how it was before you started typing; it does not undo what you already saved. If you are loading hundreds of rows, use the CSV instead of typing.',
      export_title: 'Getting data in and out',
      export_body: 'CSV uploads a file with sku, current_stock and lead_time_days: the fast way to load 500 products at once. Template downloads that same file with the columns already in place, and it is where it is worth starting.\n\n"Export PO" downloads the suggested purchase as it stands; "Export PO (edited)" downloads the quantities you corrected by hand; PDF builds the document to send to the supplier.\n\nThe order is generated grouped by supplier and recorded under Orders, so you can register the arrival later and close the loop.',
      config_title: 'The better configured, the better it buys',
      config_body: 'Lead time, cost, minimum order and service level per product or supplier. Whatever you do not give us, we assume — and we always flag it as an assumption.\n\nYou do not have to configure everything at once. Start with the products that move the most money; the rest can wait, and the app ranks them by exactly that.',
    },
  },
}
