import type { TourDefinition } from '../types'

export const inventoryTour: TourDefinition = {
  id: 'inventory-v3',
  route: '/inventory',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'inv.views', title: 'views_title', body: 'views_body' },
    { anchor: 'inv.signal', title: 'signal_title', body: 'signal_body' },
    { anchor: 'inv.coverage', title: 'coverage_title', body: 'coverage_body' },
    { anchor: 'inv.suggest', title: 'suggest_title', body: 'suggest_body' },
    { anchor: 'inv.leadtime', title: 'leadtime_title', body: 'leadtime_body' },
    { anchor: 'inv.expand', title: 'expand_title', body: 'expand_body' },
    { anchor: 'inv.export', title: 'export_title', body: 'export_body' },
    { title: 'config_title', body: 'config_body' },
  ],
  copy: {
    es: {
      name: 'Cómo leer el semáforo',
      intro_title: 'Tu catálogo entero, con el detalle completo',
      intro_body: 'El Panel de Compras te da las decisiones del día. Esta pantalla te da todo: cada producto, su cálculo y sus parámetros, para revisar y ajustar.\n\nAquí es donde se corrige la causa cuando una recomendación no te cuadra.',
      views_title: 'Tres formas de ver lo mismo',
      views_body: 'Tabla: todo el detalle, columna por columna. Es la vista para analizar.\n\nSimple: sólo lo esencial, para revisar rápido sin distraerte.\n\nProveedor: agrupado por quién te vende. Es la vista para preparar una compra, porque los pedidos se hacen por proveedor, no por producto suelto.',
      signal_title: 'El semáforo: cuatro estados y qué hacer con cada uno',
      signal_body: 'Pedir YA: se agota antes de que llegue un pedido que hagas hoy. Ya vas tarde.\n\nPedir pronto: alcanza, pero entra en la compra de esta semana.\n\nOK: cubierto, no requiere nada.\n\nSobrestock: tienes mucho más de lo que vas a vender. No es un error, es dinero parado — y a veces producto que va a caducar.\n\nLos colores están calibrados para que se distingan también con daltonismo, y nunca son la única señal: siempre hay texto.',
      coverage_title: 'Cobertura: el número que manda',
      coverage_body: 'Cuántos días (o semanas, o meses) te dura el stock actual al ritmo al que vendes.\n\nEl semáforo sale de comparar esa cobertura contra el tiempo de entrega del proveedor. Ahí está toda la lógica: si te quedan 5 días de stock y tu proveedor tarda 7, ya estás en problemas aunque la bodega se vea llena.',
      suggest_title: 'De dónde sale la cantidad sugerida',
      suggest_body: 'Cubre dos cosas: lo que vas a vender mientras el pedido viaja, más un colchón por si vendes más de lo previsto.\n\nEl tamaño del colchón lo decide tu nivel de servicio. Al 95% aceptas quedarte corto 1 de cada 20 veces; al 99% casi nunca, pero pagas mucho más inventario por esa tranquilidad.\n\nAl final redondeamos hacia arriba al mínimo que te exige el proveedor, porque pedir menos que su mínimo no es una opción real.',
      leadtime_title: 'El tiempo de entrega, y por qué lo aprendemos',
      leadtime_body: 'Es el dato que más mueve tus compras: entra en el cálculo dos veces, en lo que consumes esperando y en el tamaño del colchón.\n\nPor eso no nos quedamos con el que configuraste. Cada vez que registras una llegada medimos lo que tardó de verdad, y tras unas cuantas empezamos a usar ese número.\n\nCuando el valor es aprendido te lo indicamos, para que sepas cuándo el sistema ya sabe más que la ficha.',
      expand_title: 'Abre el cálculo de cualquier fila',
      expand_body: 'Despliega la explicación completa de ese producto: la fórmula con tus números puestos, de dónde salió cada parámetro, y un simulador para ver qué pasaría si cambiaras alguno.\n\nEs la forma de contestar «¿por qué me pide 700 unidades de esto?» sin tener que creernos.',
      export_title: 'Sacar la compra de la app',
      export_body: 'La orden se genera agrupada por proveedor. En PDF para enviarla, en CSV si tu ERP la importa, o por WhatsApp que es como se pide de verdad en muchos casos.\n\nTodo lo que exportas queda registrado en Pedidos, para que después puedas registrar la llegada y cerrar el ciclo.',
      config_title: 'Mientras mejor configurado, mejor compra',
      config_body: 'Tiempo de entrega, costo, mínimo por pedido y nivel de servicio de cada producto o proveedor. Lo que no nos des, lo asumimos — y siempre te lo marcamos como supuesto.\n\nNo hace falta configurarlo todo de golpe. Empieza por los productos que más plata mueven; el resto puede esperar, y la app te los ordena por ese criterio.',
    },
    en: {
      name: 'How to read the stock signal',
      intro_title: 'Your whole catalogue, in full detail',
      intro_body: 'The purchasing panel gives you the day\'s decisions. This screen gives you everything: every product, its calculation and its parameters, to review and adjust.\n\nThis is where you fix the cause when a recommendation does not look right.',
      views_title: 'Three ways to see the same thing',
      views_body: 'Table: full detail, column by column. The view for analysing.\n\nSimple: only the essentials, for a fast review without distraction.\n\nSupplier: grouped by who sells it to you. The view for preparing a purchase, because orders are placed per supplier, not per loose product.',
      signal_title: 'The signal: four states and what to do with each',
      signal_body: 'Order now: runs out before an order placed today could arrive. You are already late.\n\nOrder soon: it holds, but it belongs in this week\'s purchase.\n\nOK: covered, needs nothing.\n\nOverstock: far more than you will sell. Not an error — idle money, and sometimes product that will expire.\n\nThe colours are calibrated to stay distinguishable with colour blindness, and are never the only signal: there is always text.',
      coverage_title: 'Coverage: the number that drives everything',
      coverage_body: 'How many days (or weeks, or months) your current stock lasts at the rate you are selling.\n\nThe signal comes from comparing that coverage against the supplier\'s lead time. That is the whole logic: if you have 5 days of stock and your supplier takes 7, you are already in trouble no matter how full the warehouse looks.',
      suggest_title: 'Where the suggested quantity comes from',
      suggest_body: 'It covers two things: what you will sell while the order is in transit, plus a buffer in case you sell more than forecast.\n\nThe size of that buffer is set by your service level. At 95% you accept running short 1 time in 20; at 99% almost never, but you pay for it in far more inventory.\n\nFinally we round up to your supplier\'s minimum, because ordering less than their minimum is not a real option.',
      leadtime_title: 'Lead time, and why we learn it',
      leadtime_body: 'It is the single input that moves your purchasing most: it enters the calculation twice, in what you consume while waiting and in the size of the buffer.\n\nSo we do not settle for the one you configured. Every time you record an arrival we measure what it actually took, and after a few we start using that number instead.\n\nWhen a value is learned we say so, so you know when the system already knows more than the record does.',
      expand_title: 'Open the calculation on any row',
      expand_body: 'It unfolds the full explanation for that product: the formula with your numbers in it, where each parameter came from, and a simulator to see what would happen if you changed one.\n\nIt is how you answer "why is it asking me for 700 units of this?" without having to take our word for it.',
      export_title: 'Getting the purchase out of the app',
      export_body: 'The order is generated grouped by supplier. PDF to send it, CSV if your ERP imports it, or WhatsApp — which is how orders are actually placed in many cases.\n\nEverything you export is recorded under Orders, so you can register the arrival later and close the loop.',
      config_title: 'The better configured, the better it buys',
      config_body: 'Lead time, cost, minimum order and service level per product or supplier. Whatever you do not give us, we assume — and we always flag it as an assumption.\n\nYou do not have to configure everything at once. Start with the products that move the most money; the rest can wait, and the app ranks them by exactly that.',
    },
  },
}
