import type { TourDefinition } from '../types'

export const pedidosTour: TourDefinition = {
  id: 'pedidos-v2',
  route: '/pedidos',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'pedidos.pending', title: 'pending_title', body: 'pending_body' },
    { anchor: 'pedidos.table', title: 'row_title', body: 'row_body' },
    { anchor: 'pedidos.table', title: 'send_title', body: 'send_body' },
    { anchor: 'pedidos.table', title: 'receive_title', body: 'receive_body' },
    { title: 'lines_title', body: 'lines_body' },
    { title: 'confirm_title', body: 'confirm_body' },
    { anchor: 'pedidos.manual', title: 'manual_title', body: 'manual_body' },
    { anchor: 'pedidos.tabs', title: 'transfers_title', body: 'transfers_body' },
  ],
  copy: {
    es: {
      name: 'Cómo cerrar el ciclo de un pedido',
      intro_title: 'Lo que ya pediste, hasta que entra a bodega',
      intro_body: 'El Panel de Compras decide qué pedir. Esta pantalla vigila lo que ya pediste hasta que llega.\n\nExiste por una razón concreta: mientras un pedido viaja, esas unidades no están en tu bodega ni en la del proveedor, no las ve nadie. Si al llegar no las registra nadie, la app sigue creyendo que te falta producto y te lo recomienda otra vez. Aquí es donde ese ciclo se cierra.',
      pending_title: 'Los pedidos que siguen abiertos',
      pending_body: 'Este contador son las órdenes que salieron y que todavía nadie marcó como recibidas.\n\nUn número que crece semana a semana casi nunca significa que los proveedores se atrasaron: significa que la mercadería llegó y no se registró. Eso te cuesta dos veces — compras de más porque tu stock real es mayor del que vemos, y nunca aprendemos cuánto tarda de verdad ese proveedor, que es el dato que más mueve tus cantidades.',
      row_title: 'Cada fila es una decisión congelada en el tiempo',
      row_body: 'La fila guarda lo que sabías cuando decidiste: número de orden, fecha, cuántos productos entraron, cuántos estaban en rojo y cuántos a punto, las unidades y la plata comprometida. No se recalcula después, y por eso sirve para revisar una compra vieja con el contexto de ese día y no con el de hoy.\n\nAl final va el estado de recepción: pendiente, parcial o recibida. Ese es el que tienes que mover, y sólo se mueve si alguien registra la llegada.',
      send_title: 'Sacar la orden hacia el proveedor',
      send_body: '«Enviar pedido» se la manda por los medios que el proveedor tenga cargados: correo, WhatsApp o los dos. Antes de mandar nada te muestra a quién le va a llegar y a quién no — un proveedor sin contacto se saltaría en silencio.\n\nLos otros tres botones existen porque en la práctica mucho se cierra por chat. «Enviarme por WhatsApp» te manda el mensaje a ti para que tú se lo reenvíes. «Abrir en WhatsApp» abre el chat con el texto listo. «Copiar mensaje» lo deja en el portapapeles.\n\nNinguno cambia la orden ni la marca como recibida: sólo cambian por dónde sale.',
      receive_title: 'Registrar la llegada',
      receive_body: 'El botón aparece mientras la orden esté pendiente o parcial, y abre la ventana de recepción con los productos de esa orden.\n\nHazlo el día que descargas la mercadería, no a fin de mes. Registrar tarde no rompe nada, pero durante esos días la app cree que sigues sin producto y te lo va a volver a recomendar.\n\nAdemás de corregir tu stock, cada recepción mide cuánto tardó de verdad ese proveedor. Con unas cuantas dejamos de usar el tiempo de entrega configurado y usamos el real.',
      lines_title: 'La cantidad que llega ahora, línea por línea',
      lines_body: 'Cada producto trae su casilla, precargada con lo que todavía falta de esa línea. Es tu única entrada, así que anota lo que contaste al descargar.\n\nSi pediste 100 y bajaron 60, escribe 60: el pedido queda parcial y las 40 que faltan siguen esperando en vez de desaparecer. Si no llegó nada de una línea, pon 0.\n\nAnotar de más es lo caro: 100 donde llegaron 60 le suma a tu stock 40 unidades que no existen, y lo descubres el día que un cliente las pide. Anotar de menos te hace comprar dos veces lo mismo.',
      confirm_title: '«Guardar cantidades» o «Llegó todo completo»',
      confirm_body: 'Son dos caminos distintos, no un botón y su confirmación.\n\n«Guardar cantidades» registra exactamente lo que escribiste línea por línea. Es el que debes usar siempre que la entrega venga incompleta o dispareja.\n\n«Llegó todo completo» es un atajo: da por recibido todo lo pendiente de la orden e ignora lo que hayas escrito. Úsalo sólo cuando de verdad bajó todo.\n\nMarcar «llegó todo» cuando no llegó todo es peor que no registrar nada: cierras la orden, las unidades que faltan dejan de esperarse, y tu stock queda inflado.',
      manual_title: 'Los pedidos que hiciste por fuera',
      manual_body: 'Buena parte de las compras reales se hacen por teléfono o por WhatsApp, sin pasar por la app. Este botón abre una orden en blanco para cargarlas: eliges proveedor, productos y cantidades tal como los pediste.\n\nNo es burocracia: es lo que evita que mañana te recomendemos comprar otra vez algo que ya viene en camino.\n\nY una vez cargada, esa orden se recibe como cualquier otra, así que el tiempo de entrega de ese proveedor también aprende de ella.',
      transfers_title: 'Mover en vez de comprar',
      transfers_body: 'Con más de una bodega, esta pestaña muestra los traslados en camino, de dónde a dónde van y la fecha estimada de llegada.\n\nSe reciben igual que un pedido: «Registrar llegada» abre las líneas, y ahí «Llegó todo» da por recibido lo que falta o escribes cuánto llegó de cada producto y usas «Registrar cantidades». Si el traslado nunca salió, se cancela; si el resto se perdió por el camino, «Cerrar con faltante» evita que quede parcial para siempre.\n\nVan aparte de las compras porque un traslado no le suma stock a la empresa, sólo lo cambia de lugar: mezclarlos contaría el mismo producto dos veces en lo que compraste este mes.',
    },
    en: {
      name: 'How to close the loop on an order',
      intro_title: 'What you already ordered, until it reaches the warehouse',
      intro_body: 'The purchasing panel decides what to order. This screen watches what you already ordered until it arrives.\n\nIt exists for a concrete reason: while an order is in transit, those units are neither in your warehouse nor in the supplier\'s — nobody sees them. If nobody records them on arrival, the app keeps believing you are short and recommends the product again. This is where that loop is closed.',
      pending_title: 'The orders still open',
      pending_body: 'This counter is the orders that went out and that nobody has marked as received yet.\n\nA number that grows week after week almost never means the suppliers are late: it means the goods arrived and were never recorded. That costs you twice — you buy too much because your real stock is higher than we can see, and we never learn how long that supplier actually takes, which is the input that moves your quantities most.',
      row_title: 'Every row is a decision frozen in time',
      row_body: 'The row keeps what you knew when you decided: order number, date, how many products went in, how many were already in the red and how many were about to be, the units and the money committed. It is not recomputed later, which is what lets you review an old purchase with that day\'s context instead of today\'s.\n\nAt the end sits the reception status: pending, partial or received. That is the one you have to move, and it only moves if somebody records the arrival.',
      send_title: 'Getting the order to the supplier',
      send_body: '"Send order" delivers it through whatever the supplier has on file: email, WhatsApp or both. Before sending anything it shows you who will get it and who will not — a supplier with no contact would be skipped in silence.\n\nThe other three buttons exist because in practice a lot gets closed over chat. "Send to my WhatsApp" sends the message to you so you can forward it. "Open in WhatsApp" opens the chat with the text ready. "Copy message" puts it on the clipboard.\n\nNone of them changes the order or marks it received: they only change how it leaves.',
      receive_title: 'Recording the arrival',
      receive_body: 'The button is there while the order is pending or partial, and it opens the reception window with that order\'s products.\n\nDo it the day you unload the goods, not at month end. Recording late breaks nothing, but for those days the app believes you are still short and will recommend the product again.\n\nBesides correcting your stock, every reception measures how long that supplier really took. After a few we stop using the configured lead time and use the real one.',
      lines_title: 'The quantity arriving now, line by line',
      lines_body: 'Each product has its own box, pre-filled with what is still outstanding on that line. It is your only input, so write down what you counted while unloading.\n\nIf you ordered 100 and 60 came off the truck, put 60: the order stays partial and the missing 40 keep waiting instead of disappearing. If nothing arrived for a line, put 0.\n\nOver-recording is the expensive one: 100 where 60 arrived adds 40 units to your stock that do not exist, and you find out the day a customer asks for them. Under-recording makes you buy the same thing twice.',
      confirm_title: '"Save quantities" or "Everything arrived"',
      confirm_body: 'These are two different paths, not a button and its confirmation.\n\n"Save quantities" records exactly what you typed, line by line. It is the one to use whenever the delivery comes in incomplete or uneven.\n\n"Everything arrived" is a shortcut: it takes all the outstanding units of the order as received and ignores whatever you typed. Use it only when everything genuinely came off the truck.\n\nMarking "everything arrived" when it did not is worse than recording nothing: you close the order, the missing units stop being expected, and your stock is left inflated.',
      manual_title: 'The orders you placed outside the app',
      manual_body: 'A good share of real purchasing happens by phone or WhatsApp, never touching the app. This button opens a blank order to enter them: you pick the supplier, the products and the quantities exactly as you ordered them.\n\nIt is not paperwork: it is what stops us from recommending tomorrow that you buy again something already on its way.\n\nAnd once entered, that order is received like any other, so the supplier\'s lead time learns from it too.',
      transfers_title: 'Moving instead of buying',
      transfers_body: 'With more than one warehouse, this tab shows the transfers in transit, where they go from and to, and the estimated arrival date.\n\nThey are received like an order: "Record arrival" opens the lines, and there "Everything arrived" takes the outstanding units as received, or you type how much of each product came and use "Record quantities". If the transfer never left, cancel it; if the remainder was lost on the way, "Close with loss" keeps it from sitting partial forever.\n\nThey sit apart from purchases because a transfer adds no stock to the company, it only moves it: mixing them would count the same product twice in what you bought this month.',
    },
  },
}
