import type { TourDefinition } from '../types'

export const quickStartTour: TourDefinition = {
  id: 'quickStart-v4',
  route: '/ventas',
  name: 'name',
  autoStart: true,
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'qs.steps', title: 'steps_title', body: 'steps_body' },
    { anchor: 'qs.name', title: 'name_title', body: 'name_body' },
    { anchor: 'qs.horizon', title: 'horizon_title', body: 'horizon_body' },
    { anchor: 'qs.granularity', title: 'granularity_title', body: 'granularity_body' },
    { anchor: 'qs.tabs', title: 'tabs_title', body: 'tabs_body' },
    { anchor: 'qs.upload', title: 'upload_title', body: 'upload_body' },
    { anchor: 'qs.example', title: 'example_title', body: 'example_body' },
    { anchor: 'qs.demo', title: 'demo_title', body: 'demo_body' },
    { title: 'mapping_title', body: 'mapping_body' },
    { title: 'training_title', body: 'training_body' },
    { title: 'wait_title', body: 'wait_body' },
  ],
  copy: {
    es: {
      name: 'Cómo entrenar tus predicciones',
      intro_title: 'De un archivo de ventas a saber qué comprar',
      intro_body: 'Esta pantalla convierte tu historial de ventas en una predicción de demanda, y esa predicción en un semáforo que te dice qué pedir, cuánto y cuándo.\n\nLo único que tienes que aportar es el archivo y tres decisiones. Todo lo demás lo hacemos nosotros y te lo explicamos por el camino.',
      steps_title: 'Los tres pasos, y cuál es el que importa',
      steps_body: 'Paso 1: eliges el plan (nombre, hasta cuándo, con qué detalle) y subes el archivo. Paso 2: confirmas qué columna es cuál. Paso 3: entrenamos.\n\nEl paso 2 existe porque cada sistema exporta con nombres distintos, y si confundimos la columna de fecha con otra, todo lo que venga después está mal. Intentamos adivinarlo solo; sólo te preguntamos lo que no podemos deducir con seguridad.',
      name_title: 'Nombre: es para ti, no para el modelo',
      name_body: 'Campo de texto libre, opcional, hasta 200 caracteres. No afecta a ningún cálculo: sirve para que dentro de tres meses, con seis entrenamientos hechos, sepas cuál es cuál.\n\nLo que de verdad ayuda es el período de los datos o el motivo: «ventas ene–jun 2026», «julio después de subir precios». Lo que no ayuda: «prueba», «prueba 2», «prueba final» — en la pantalla de sesiones vas a ver tres filas idénticas y ninguna te va a decir cuál era cuál.\n\nSi lo dejas vacío le ponemos la fecha del día.',
      horizon_title: 'Hasta cuándo planificar: mídelo contra tu proveedor',
      horizon_body: 'Tres opciones: 4 semanas, 8 semanas o 6 meses. Es cuánto futuro te vamos a predecir.\n\nLa regla: tiene que cubrir al menos lo que tarda tu proveedor en entregarte, más el tiempo hasta tu próximo pedido. Si tu proveedor tarda 30 días, 4 semanas (28 días) se te queda corto justo para el pedido que estás por hacer — elige 8 semanas y te queda margen.\n\nY más no siempre es mejor: pedir 6 meses con un año de historial produce números que parecen precisos y no lo son. Elige lo que necesitas para comprar, no el máximo.',
      granularity_title: 'Nivel de detalle: el ritmo en el que compras',
      granularity_body: 'Define en qué unidad predecimos: unidades por día, por semana o por mes.\n\n«Auto» lee la frecuencia real de tu archivo y decide por ti — es la opción correcta si no tienes un motivo concreto para forzar otra.\n\nSi eliges a mano, elige el ritmo en el que de verdad haces pedidos. Compras una vez por semana: «Semanal». Predecir por día te da un detalle que no vas a usar y hace el modelo más frágil, porque la venta diaria de un producto rota es mucho más ruidosa que la semanal.\n\nY si tus datos ya vienen sumados por mes, no elijas «Diario»: repartiríamos ese mes en 30 días iguales, inventando un detalle que tu archivo no tiene.',
      tabs_title: 'Tres formas de empezar, no una',
      tabs_body: '«Subir archivo nuevo» es para un archivo que aún no está en Faro.\n\n«Usar un archivo ya subido» reutiliza uno del servidor: útil cuando quieres probar otro horizonte o otro detalle sobre los mismos datos, sin volver a subir nada.\n\n«Repetir una carga anterior» va más lejos: se lleva también el mapeo de columnas, o sea que te saltas el paso 2 entero. Es la vía rápida para el reentrenamiento de cada mes.\n\nLas dos últimas sólo aparecen cuando ya tienes archivos o entrenamientos previos.',
      upload_title: 'La zona de carga: qué archivo sirve',
      upload_body: 'Arrastra el archivo aquí o haz clic para buscarlo. Aceptamos CSV y Excel (.xlsx, .xls), tal cual te lo exporta tu sistema; no hace falta que lo limpies.\n\nNecesita como mínimo tres columnas: qué producto, en qué fecha, cuánto se vendió. Reconocemos los nombres más comunes en español e inglés (fecha, date, ventas, cantidad, sku, código…).\n\nSi es un CSV lo revisamos aquí mismo, antes de subirlo, y te decimos el número de fila exacta de cada problema. Cuanto más historial, mejor: con menos de 20 períodos por producto el modelo tiene poco de dónde aprender y te lo vamos a decir.',
      example_title: 'Así se ve un archivo que funciona',
      example_body: 'Tres columnas y una fila por producto y fecha. Nada más.\n\nLo que hace que falle casi siempre es esto: fechas escritas de dos maneras en el mismo archivo, cantidades con símbolo de moneda o separador de miles («$1,250» no es un número), una fila de totales al final, y el mismo producto escrito de dos formas («SKU-001» y «sku 001» se vuelven dos productos distintos y ninguno junta historia suficiente).\n\nSi prefieres partir de algo que ya está bien armado, el botón de plantilla que está aquí arriba te descarga este mismo ejemplo en CSV.',
      demo_title: 'Probar sin archivo',
      demo_body: 'Si aún no tienes tu exportación a la mano, este botón carga ventas ficticias de 5 productos, entrena de verdad y te deja en el semáforo en un par de minutos.\n\nSirve para ver cómo se lee el resultado antes de invertir tiempo preparando tus datos. No toca nada tuyo: crea su propio entrenamiento aparte, y el nombre, el horizonte y el detalle que elegiste arriba también se le aplican.',
      mapping_title: 'Paso 2: decirnos qué columna es cuál',
      mapping_body: 'Cuando el archivo suba verás una lista de campos con un desplegable al lado. Sólo tres son obligatorios y van marcados con ★: SKU (el código del producto), Fecha y Demanda (las unidades vendidas).\n\nEl resto son opcionales y te decimos qué valor asumimos si los dejas en «no está en el archivo» — por ejemplo, lead time 15 días. Mapear Costo y Precio si los tienes hace que después el semáforo pueda hablarte de plata, no sólo de unidades.\n\nRevisa Fecha con especial cuidado: si apuntamos a la columna equivocada el entrenamiento no falla, simplemente aprende una historia que no ocurrió.',
      training_title: 'Qué pasa mientras esperas',
      training_body: 'No entrenamos un modelo: entrenamos varios y nos quedamos con el mejor para cada producto, uno por uno.\n\nUn producto de venta estable y otro que se vende a saltos no se predicen igual, así que a cada uno le toca el modelo que mejor le funcionó a él.\n\nY no nos creemos el resultado sin comprobarlo: cada modelo se mide contra trozos de tu propio historial que no vio al entrenar, y contra métodos ingenuos («vende lo mismo que ayer»). Un modelo que no le gana a eso no merece decidir tus compras.',
      wait_title: 'Puedes cerrar la pestaña',
      wait_body: 'Tarda unos minutos según cuántos productos tengas. El entrenamiento corre en nuestro servidor, no en tu navegador, así que puedes irte y volver.\n\nCuando termine te llevamos al semáforo. Si algo en tus datos nos dio problemas — fechas raras, cantidades negativas, productos con historial insuficiente — te lo listamos en vez de esconderlo. Y si algo falla, el botón de reintentar no te obliga a volver a subir el archivo: ya está en el servidor.',
    },
    en: {
      name: 'How to train your forecasts',
      intro_title: 'From a sales file to knowing what to buy',
      intro_body: 'This screen turns your sales history into a demand forecast, and that forecast into a stock signal telling you what to order, how much, and when.\n\nAll you provide is the file and three decisions. We do the rest, and explain it as we go.',
      steps_title: 'Three steps, and which one matters',
      steps_body: 'Step 1: choose the plan (name, how far ahead, at what detail) and upload the file. Step 2: confirm which column is which. Step 3: we train.\n\nStep 2 exists because every system exports with different names, and if we mistake the date column for another, everything downstream is wrong. We try to detect it automatically and only ask about what we cannot safely infer.',
      name_title: 'Name: it is for you, not the model',
      name_body: 'A free-text field, optional, up to 200 characters. It affects no calculation: it is so that in three months, with six trainings behind you, you can tell them apart.\n\nWhat actually helps is the data period or the reason: "sales Jan–Jun 2026", "July after the price rise". What does not help: "test", "test 2", "final test" — on the sessions screen you will see three identical rows and none of them will tell you which was which.\n\nLeave it empty and we use today\'s date.',
      horizon_title: 'How far ahead: measure it against your supplier',
      horizon_body: 'Three options: 4 weeks, 8 weeks or 6 months. It is how much future we forecast.\n\nThe rule: it must cover at least your supplier\'s delivery time, plus the time until your next order. If your supplier takes 30 days, 4 weeks (28 days) falls short for exactly the order you are about to place — pick 8 weeks and you have margin.\n\nAnd more is not always better: asking for 6 months from one year of history produces numbers that look precise and are not. Pick what you need in order to buy, not the maximum.',
      granularity_title: 'Detail level: the rhythm you buy in',
      granularity_body: 'This sets the unit we forecast in: units per day, per week, or per month.\n\n"Auto" reads your file\'s real frequency and decides for you — it is the right choice unless you have a concrete reason to force another.\n\nIf you pick by hand, pick the rhythm you actually order in. Buying once a week: "Weekly". Forecasting daily gives you detail you will never use and makes the model more fragile, because daily sales of a slow-moving product are far noisier than weekly ones.\n\nAnd if your data already comes summed by month, do not pick "Daily": we would spread that month across 30 equal days, inventing detail your file does not contain.',
      tabs_title: 'Three ways to start, not one',
      tabs_body: '"Upload a new file" is for a file that is not in Faro yet.\n\n"Use a file already uploaded" reuses one from the server — useful when you want to try a different horizon or detail level on the same data without uploading again.\n\n"Repeat a previous load" goes further: it carries the column mapping too, so you skip step 2 entirely. That is the fast path for a monthly retrain.\n\nThe last two only appear once you have previous files or trainings.',
      upload_title: 'The drop zone: what file works',
      upload_body: 'Drag the file here or click to browse. We accept CSV and Excel (.xlsx, .xls), exactly as your system exports it; no need to clean it up.\n\nIt needs three columns at minimum: which product, on what date, how much sold. We recognise the common names in Spanish and English (fecha, date, ventas, cantidad, sku, code…).\n\nIf it is a CSV we check it right here, before uploading, and tell you the exact row number of each problem. More history is better: under 20 periods per product the model has little to learn from, and we will say so.',
      example_title: 'This is what a working file looks like',
      example_body: 'Three columns and one row per product and date. Nothing more.\n\nWhat breaks it almost every time: dates written two different ways in the same file, quantities carrying a currency symbol or thousands separator ("$1,250" is not a number), a totals row at the bottom, and the same product spelled two ways ("SKU-001" and "sku 001" become two separate products and neither gathers enough history).\n\nIf you would rather start from something already correct, the template button just above downloads this same example as a CSV.',
      demo_title: 'Try it without a file',
      demo_body: 'If you do not have your export handy yet, this button loads fictional sales for 5 products, really trains on them, and drops you on the stock signal in a couple of minutes.\n\nIt is there so you can see how the result reads before investing time preparing your own data. It touches nothing of yours: it creates its own separate training, and the name, horizon and detail level you chose above apply to it too.',
      mapping_title: 'Step 2: telling us which column is which',
      mapping_body: 'Once the file uploads you will see a list of fields, each with a dropdown beside it. Only three are required and they are marked with ★: SKU (the product code), Date, and Demand (the units sold).\n\nThe rest are optional and we tell you what we assume if you leave them as "not in the file" — lead time of 15 days, for example. Mapping Cost and Price when you have them is what later lets the stock signal talk to you in money, not only in units.\n\nCheck Date with particular care: if we point at the wrong column the training does not fail, it simply learns a history that never happened.',
      training_title: 'What happens while you wait',
      training_body: 'We do not train one model: we train several and keep the best one for each product, individually.\n\nA steady seller and a lumpy one are not forecast the same way, so each gets the model that actually worked for it.\n\nAnd we do not take the result on faith: every model is scored against slices of your own history it never saw while training, and against naive methods ("sells the same as yesterday"). A model that cannot beat that does not get to decide your purchasing.',
      wait_title: 'You can close the tab',
      wait_body: 'It takes a few minutes depending on how many products you have. Training runs on our server, not in your browser, so you can leave and come back.\n\nWhen it finishes we take you to the stock signal. If anything in your data gave us trouble — odd dates, negative quantities, products with too little history — we list it rather than hide it. And if something fails, the retry button does not make you upload the file again: it is already on the server.',
    },
  },
}
