import type { TourDefinition } from '../types'

export const quickStartTour: TourDefinition = {
  id: 'quickStart-v3',
  route: '/quick-start',
  name: 'name',
  autoStart: true,
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'qs.steps', title: 'steps_title', body: 'steps_body' },
    { anchor: 'qs.tabs', title: 'tabs_title', body: 'tabs_body' },
    { anchor: 'qs.upload', title: 'upload_title', body: 'upload_body' },
    { anchor: 'qs.name', title: 'name_title', body: 'name_body' },
    { anchor: 'qs.horizon', title: 'horizon_title', body: 'horizon_body' },
    { anchor: 'qs.granularity', title: 'granularity_title', body: 'granularity_body' },
    { title: 'training_title', body: 'training_body' },
    { title: 'wait_title', body: 'wait_body' },
  ],
  copy: {
    es: {
      name: 'Cómo entrenar tus predicciones',
      intro_title: 'De un archivo de ventas a saber qué comprar',
      intro_body: 'Esta pantalla convierte tu historial de ventas en una predicción de demanda, y esa predicción en un semáforo que te dice qué pedir, cuánto y cuándo.\n\nLo único que tienes que aportar es el archivo y tres decisiones. Todo lo demás lo hacemos nosotros y te lo explicamos por el camino.',
      steps_title: 'Los tres pasos, y cuál es el que importa',
      steps_body: 'Paso 1: subes el archivo. Paso 2: confirmas qué columna es cuál. Paso 3: entrenamos.\n\nEl paso 2 existe porque cada sistema exporta con nombres distintos, y si confundimos la columna de fecha con otra, todo lo que venga después está mal. Intentamos adivinarlo solo; sólo te preguntamos lo que no podemos deducir con seguridad.',
      tabs_title: 'Tres formas de empezar, no una',
      tabs_body: '«Cargar ventas» es para un archivo nuevo.\n\n«Mis archivos» reutiliza uno que ya subiste: útil cuando quieres probar otro horizonte o otra granularidad sobre los mismos datos, sin volver a subir nada.\n\nSi además clonas una sesión anterior, se lleva también el mapeo de columnas — o sea que te saltas el paso 2 entero. Es la vía rápida para el reentrenamiento de cada mes.',
      upload_title: 'Qué archivo sirve, y qué hacemos con él',
      upload_body: 'CSV o Excel, tal cual te lo exporta tu sistema. No hace falta que lo limpies.\n\nNecesita como mínimo tres cosas: qué producto, en qué fecha, cuánto se vendió. Reconocemos los nombres de columna más comunes en español e inglés (fecha, date, ventas, cantidad, sku, código…).\n\nCuanto más historial, mejor: con menos de 20 períodos por producto el modelo tiene poco de dónde aprender y te lo vamos a decir. Lo leemos sólo para entrenar; no se comparte con nadie.',
      name_title: 'El nombre es para ti, no para el modelo',
      name_body: 'No afecta a ningún cálculo. Sirve para que dentro de tres meses, con seis entrenamientos hechos, sepas cuál es cuál.\n\nLo útil suele ser el período de los datos o el motivo: «ventas ene–jun», «después de subir precios». Si lo dejas vacío le ponemos la fecha.',
      horizon_title: 'Hasta dónde predecir: mide contra tu proveedor',
      horizon_body: 'El horizonte es cuánto futuro te predecimos.\n\nLa regla es sencilla: tiene que cubrir al menos lo que tarda tu proveedor en entregarte. Si pides con 30 días de anticipación y predices sólo 15, la predicción no llega a cubrir el pedido que estás por hacer — no te sirve para decidir.\n\nY más no siempre es mejor: predecir a 6 meses con un año de historial produce números que parecen precisos y no lo son. Elige lo que necesitas para comprar, no lo máximo posible.',
      granularity_title: 'En qué ritmo compras: diario, semanal o mensual',
      granularity_body: 'Esto define en qué unidad predecimos: unidades por día, por semana o por mes.\n\nElige el ritmo en el que de verdad haces pedidos. Si compras una vez por semana, predecir por día te da un detalle que no vas a usar y hace el modelo más frágil: la venta diaria de un producto rota es mucho más ruidosa que la semanal.\n\nSi tus datos vienen agregados por mes, no elijas diario. Repartiríamos ese mes en 30 días iguales, inventando un detalle que tus datos no tienen.',
      training_title: 'Qué pasa mientras esperas',
      training_body: 'No entrenamos un modelo: entrenamos varios y nos quedamos con el mejor para cada producto, uno por uno.\n\nUn producto de venta estable y otro que se vende a saltos no se predicen igual, así que a cada uno le toca el modelo que mejor le funcionó a él.\n\nY no nos creemos el resultado sin comprobarlo: cada modelo se mide contra trozos de tu propio historial que no vio al entrenar, y contra métodos ingenuos («vende lo mismo que ayer»). Un modelo que no le gana a eso no merece decidir tus compras.',
      wait_title: 'Puedes cerrar la pestaña',
      wait_body: 'Tarda unos minutos según cuántos productos tengas. El entrenamiento corre en nuestro servidor, no en tu navegador, así que puedes irte y volver.\n\nCuando termine te llevamos al semáforo. Si algo en tus datos nos dio problemas — fechas raras, cantidades negativas, productos con historial insuficiente — te lo listamos en vez de esconderlo.',
    },
    en: {
      name: 'How to train your forecasts',
      intro_title: 'From a sales file to knowing what to buy',
      intro_body: 'This screen turns your sales history into a demand forecast, and that forecast into a stock signal telling you what to order, how much, and when.\n\nAll you provide is the file and three decisions. We do the rest, and explain it as we go.',
      steps_title: 'Three steps, and which one matters',
      steps_body: 'Step 1: upload the file. Step 2: confirm which column is which. Step 3: we train.\n\nStep 2 exists because every system exports with different names, and if we mistake the date column for another, everything downstream is wrong. We try to detect it automatically and only ask about what we cannot safely infer.',
      tabs_title: 'Three ways to start, not one',
      tabs_body: '"Upload sales" is for a new file.\n\n"My files" reuses one you already uploaded — useful when you want to try a different horizon or granularity on the same data without uploading again.\n\nCloning a previous session goes further: it carries the column mapping too, so you skip step 2 entirely. That is the fast path for a monthly retrain.',
      upload_title: 'What file works, and what we do with it',
      upload_body: 'CSV or Excel, exactly as your system exports it. No need to clean it up.\n\nIt needs three things at minimum: which product, on what date, how much sold. We recognise the common column names in Spanish and English (fecha, date, ventas, cantidad, sku, code…).\n\nMore history is better: under 20 periods per product the model has little to learn from, and we will say so. We read it only to train; it is not shared with anyone.',
      name_title: 'The name is for you, not the model',
      name_body: 'It affects no calculation. It is so that in three months, with six trainings behind you, you can tell them apart.\n\nWhat usually helps is the data period or the reason: "sales Jan–Jun", "after the price rise". Leave it empty and we use the date.',
      horizon_title: 'How far ahead: measure against your supplier',
      horizon_body: 'The horizon is how much future we forecast.\n\nThe rule is simple: it must cover at least your supplier\'s delivery time. If you order 30 days ahead and forecast only 15, the forecast does not reach the order you are about to place — it cannot inform the decision.\n\nAnd more is not always better: forecasting six months from one year of history produces numbers that look precise and are not. Pick what you need in order to buy, not the maximum available.',
      granularity_title: 'The rhythm you buy in: daily, weekly or monthly',
      granularity_body: 'This sets the unit we forecast in: units per day, per week, or per month.\n\nPick the rhythm you actually order in. If you buy once a week, forecasting daily gives you detail you will never use and makes the model more fragile: daily sales of a slow-moving product are far noisier than weekly ones.\n\nIf your data is already aggregated monthly, do not pick daily. We would spread that month across 30 equal days, inventing detail your data does not contain.',
      training_title: 'What happens while you wait',
      training_body: 'We do not train one model: we train several and keep the best one for each product, individually.\n\nA steady seller and a lumpy one are not forecast the same way, so each gets the model that actually worked for it.\n\nAnd we do not take the result on faith: every model is scored against slices of your own history it never saw while training, and against naive methods ("sells the same as yesterday"). A model that cannot beat that does not get to decide your purchasing.',
      wait_title: 'You can close the tab',
      wait_body: 'It takes a few minutes depending on how many products you have. Training runs on our server, not in your browser, so you can leave and come back.\n\nWhen it finishes we take you to the stock signal. If anything in your data gave us trouble — odd dates, negative quantities, products with too little history — we list it rather than hide it.',
    },
  },
}
