import type { TourDefinition } from '../types'

export const roiTour: TourDefinition = {
  id: 'roi-v2',
  route: '/impacto',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'roi.recap', title: 'recap_title', body: 'recap_body' },
    { anchor: 'roi.recap_orders', title: 'recap_orders_title', body: 'recap_orders_body' },
    { anchor: 'roi.recap_adoption', title: 'recap_adoption_title', body: 'recap_adoption_body' },
    { anchor: 'roi.recap_risks', title: 'recap_risks_title', body: 'recap_risks_body' },
    { anchor: 'roi.recap_capital', title: 'recap_capital_title', body: 'recap_capital_body' },
    { anchor: 'roi.recap_managed', title: 'recap_managed_title', body: 'recap_managed_body' },
    { anchor: 'roi.hero', title: 'hero_title', body: 'hero_body' },
    { anchor: 'roi.hero_orders', title: 'hero_orders_title', body: 'hero_orders_body' },
    { anchor: 'roi.hero_risks', title: 'hero_risks_title', body: 'hero_risks_body' },
    { anchor: 'roi.hero_value', title: 'hero_value_title', body: 'hero_value_body' },
    { anchor: 'roi.adoption', title: 'adoption_title', body: 'adoption_body' },
    { anchor: 'roi.monthly', title: 'monthly_title', body: 'monthly_body' },
    { anchor: 'roi.monthly_cols', title: 'columns_title', body: 'columns_body' },
    { anchor: 'roi.orders', title: 'orders_link_title', body: 'orders_link_body' },
    { anchor: 'roi.back', title: 'back_title', body: 'back_body' },
    { anchor: 'roi.why', title: 'why_title', body: 'why_body' },
  ],
  copy: {
    es: {
      name: 'Qué se cuenta aquí, y qué no',
      intro_title: 'Sólo lo que quedó registrado',
      intro_body: 'Casi cualquier herramienta de inventario te promete un ahorro. Nosotros no podemos medirlo: nadie sabe qué habría pasado si no hubieras pedido, así que un número de «quiebres evitados» o «plata ahorrada» sería inventado con buena letra.\n\nLo que ves aquí son hechos: órdenes que generaste, riesgos sobre los que actuaste, plata que movieron esas compras. Menos vistoso que una promesa, pero es lo que sí podemos sostener frente a ti.\n\nEsta pantalla no tiene nada que llenar: son cifras y dos enlaces. Te vamos a decir qué cuenta cada una y qué deberías hacer al verla.',
      recap_title: 'El mes cerrado, idéntico al del correo',
      recap_body: 'Este bloque resume el último mes completo — no el mes en curso —, y es exactamente el que te llega por correo el primer día del mes. No hay una versión bonita para la pantalla y otra para el correo.\n\nSi ese mes no generaste ninguna orden, no verás ceros: verás «Aún no hay suficiente historial para calcular esto». Un cero se lee como «no pasó nada»; decir que no hay con qué se lee como lo que de verdad es.\n\nLas cinco casillas de abajo son las cinco cifras del correo. Vamos una por una.',
      recap_orders_title: 'Órdenes generadas: cuenta pedidos, no productos',
      recap_orders_body: 'Cuántas órdenes de compra saliste a generar desde Faro en ese mes. Suma una por orden, sin importar cuántas líneas llevara: un pedido con 30 productos cuenta 1, no 30.\n\nLo que NO cuenta: lo que pediste por WhatsApp o teléfono sin registrarlo aquí, y las recepciones (eso se lleva en Pedidos).\n\nSi compras semanalmente, 4 o 5 al mes es lo normal. Si ves 1 y sabes que hiciste diez compras, el problema no es la cifra: es que nueve compras se están decidiendo fuera de Faro.',
      recap_adoption_title: 'Adopción del mes: cuánto le hiciste caso',
      recap_adoption_body: 'De las líneas que Faro te propuso en el carrito ese mes, qué porcentaje te llevaste — tal cual o cambiándole la cantidad. Debajo tienes los dos números crudos: «Seguiste 34 de 50 líneas».\n\nCuenta líneas propuestas, no productos distintos: si el mismo SKU apareció en dos pedidos, cuenta dos veces.\n\nUn 90% dice que revisas y aceptas. Un 30% dice que casi todo lo corriges a mano, y eso no se arregla mirando esta pantalla: se arregla en la ficha del proveedor (tiempo de entrega, nivel de servicio).',
      recap_risks_title: 'Riesgos atendidos: acciones, no quiebres evitados',
      recap_risks_body: 'Líneas marcadas «Pedir ya» que sí ordenaste dentro del mes. Es una cuenta de lo que hiciste. No es «quiebres que evitaste»: nunca vamos a ver qué habría pasado sin ese pedido, así que no lo inventamos.\n\nOjo con leerlo como un logro. Si mes tras mes es alto, significa que estás llegando al rojo muy seguido. Lo sano es verlo bajar mientras las órdenes se mantienen: eso es pedir con tiempo en vez de apagar incendios.\n\nUn 0 con órdenes generadas no es un vacío: es el mes ideal — compraste sin que ningún producto llegara a urgente.',
      recap_capital_title: 'Capital liberado: resta de dos mediciones',
      recap_capital_body: 'Cuánto bajó el valor de tu inventario en sobrestock durante el mes. Sale de restar dos fotos reales de tu inventario: la del día 1 de ese mes menos la del día 1 del siguiente. Nada modelado.\n\n«No disponible» aquí significa una de dos cosas, y ninguna es un cero: falta una de las dos fotos (llevas menos de dos meses midiendo) o el sobrestock creció en vez de bajar. Un aumento no es un ahorro, y ponerlo en 0 se leería como «no lograste nada» cuando lo cierto es «esto no ocurrió».',
      recap_managed_title: 'Compras gestionadas: unidades × costo',
      recap_managed_body: 'El valor de lo que ordenaste: unidades pedidas multiplicadas por el costo unitario que tú cargaste en cada SKU. Es plata movida — no es margen, no es venta, y no incluye las líneas que descartaste del carrito.\n\n«No disponible» aquí significa algo muy concreto: ninguna línea de ese mes traía costo unitario. Se arregla en un solo lugar — carga el costo en la ficha de tus SKUs y el siguiente resumen ya sale en dinero. Mientras tanto no rellenamos con un promedio inventado.',
      hero_title: 'Debajo, los acumulados de siempre',
      hero_body: 'Los tres números grandes no son del mes: son de toda tu historia con Faro, desde tu primera orden. Por eso sólo suben, y por eso no se comparan con las casillas de arriba.\n\nLéelos siempre junto a la ventana de tiempo que trae el primero («desde 4 de marzo · 120 días activo»). Doce órdenes en 40 días son un ritmo semanal; las mismas doce en 400 días son otra cosa completamente distinta.',
      hero_orders_title: 'Órdenes generadas (histórico)',
      hero_orders_body: 'Todas las órdenes que has generado desde Faro, contadas igual que arriba: una por pedido.\n\nDebajo va la fecha de la primera y los días transcurridos desde entonces. Esa ventana es la que da sentido al resto de la pantalla: si son muchos días y pocas órdenes, la mayoría de tus compras se están decidiendo fuera y todo lo demás se va a ver flaco — no porque midamos mal, sino porque no hay qué medir.',
      hero_risks_title: 'Riesgos de quiebre atendidos (histórico)',
      hero_risks_body: 'Total de líneas «Pedir ya» que ordenaste desde que usas Faro. Otra vez: acciones registradas, no quiebres evitados.\n\nEl número solo dice poco; compáralo con las órdenes de al lado. 20 órdenes y 120 riesgos atendidos son seis urgencias por pedido: estás comprando en modo apagafuegos. La misma cuenta con 20 y 25 dice que casi todo lo pediste antes de que entrara en rojo, que es exactamente para lo que existe el semáforo.',
      hero_value_title: 'Plata gestionada (histórico)',
      hero_value_body: 'La suma de unidades × costo unitario de todo lo que has ordenado. Plata que movieron tus compras, no plata ahorrada.\n\nSi en lugar de dinero ves un número ámbar de «unidades totales ordenadas», no es una falla de la pantalla: ninguna de tus órdenes traía costo unitario. Es la única cifra de aquí que puedes arreglar tú hoy — pon el costo en tus SKUs y la próxima orden ya suma en dinero. Las órdenes viejas se quedan como están: cada una guardó el costo que tenía el día que la generaste.',
      adoption_title: 'La cifra que de verdad te sirve',
      adoption_body: 'De cada cien líneas que te pusimos enfrente, cuántas te llevaste. La tarjeta se pinta verde desde 70%, ámbar entre 40 y 70, roja por debajo de 40.\n\nBaja no significa que seas desobediente: significa que las cantidades no te cuadran, y la causa casi siempre son tiempos de entrega o niveles de servicio mal puestos. La línea gris de abajo («X descartadas») es tu lista de trabajo: son las líneas que quitaste del carrito.\n\nSi esta tarjeta no aparece, es que aún no has aprobado ni descartado nada.',
      monthly_title: 'Mes a mes, para ver la tendencia',
      monthly_body: 'La misma cuenta repetida por mes, los últimos seis, del más reciente al más viejo. Sirve para una pregunta que sí tiene respuesta honesta: ¿estás pidiendo más a tiempo que antes, y estás confiando más en lo que te sugiere?\n\nUna fila en blanco no es un error: es un mes en el que no generaste órdenes. Y el mes en curso aparece incompleto, porque todavía le faltan días.',
      columns_title: 'Qué mide cada columna',
      columns_body: 'Mes: el mes calendario.\nPedidos: cuántas órdenes generaste.\nRiesgos de quiebre atendidos: líneas «Pedir ya» que ordenaste; se pinta en rojo cuando hay alguna.\nValor gestionado: unidades × costo unitario; sale en 0 si tus SKUs no tienen costo cargado.\n% Adopción: aceptadas ÷ propuestas, con «—» cuando ese mes no te propusimos nada.\nCapital liberado: sólo aparece cuando existen las dos fotos del inventario; si no, dice que aún no hay suficiente historial en vez de inventar la resta.',
      orders_link_title: 'Ver pedidos y registrar llegadas',
      orders_link_body: 'Este enlace te lleva a donde vive cada orden: qué llevaba, a qué proveedor y el botón para marcar que llegó.\n\nRegistrar la llegada no es papeleo. Cada recepción le enseña a Faro cuánto tarda de verdad ese proveedor, y ese tiempo real es el que después decide cuándo te avisa que pidas. Si nunca registras llegadas, el sistema sigue creyendo el plazo que alguien escribió a mano el primer día — y ahí nacen la mitad de las recomendaciones que no te cuadran.',
      back_title: 'Volver a Inventario',
      back_body: 'Te regresa al semáforo, que es donde de verdad se decide qué pedir hoy.\n\nAquí no hay nada que puedas romper: esta pantalla sólo lee y cuenta, no cambia ningún dato tuyo. Entra y sal las veces que quieras.\n\nLo que sí mueve estos números está del otro lado: cada orden que generes desde el semáforo aparece en esta pantalla, y en el resumen del mes siguiente.',
      why_title: 'Por qué no te prometemos un ahorro',
      why_body: 'Un quiebre evitado no se puede medir: habría que saber cuánto habrías vendido con un stock que nunca existió. Quien te da ese número lo está modelando, no midiendo — y te lo cobra igual.\n\nLo que sí puedes hacer con esta pantalla es una comparación honesta contigo mismo: si tu adopción sube y tus riesgos atendidos bajan sin que caigan las órdenes, estás comprando mejor. Si no, la pantalla te lo dice sin maquillaje, que es para lo que existe.',
    },
    en: {
      name: 'What is counted here, and what is not',
      intro_title: 'Only what was actually recorded',
      intro_body: 'Almost every inventory tool promises you a saving. We cannot measure one: nobody knows what would have happened if you had not ordered, so a "stockouts avoided" or "money saved" figure would be invented in neat handwriting.\n\nWhat you see here are facts: orders you generated, risks you acted on, money those purchases moved. Less impressive than a promise, but it is what we can defend to your face.\n\nThere is nothing to fill in on this screen: it is figures and two links. We will tell you what each one counts and what it should make you do.',
      recap_title: 'The closed month, identical to the email',
      recap_body: 'This block summarises the last complete month — not the month in progress — and it is exactly the one that reaches you by email on the first day of the month. There is no pretty version for the screen and another for the mail.\n\nIf you generated no order that month you will not see zeros: you will see "Not enough history to calculate this yet". A zero reads as "nothing happened"; saying there is no basis reads as what it really is.\n\nThe five tiles below are the five figures in the email. One at a time.',
      recap_orders_title: 'Orders generated: it counts orders, not products',
      recap_orders_body: 'How many purchase orders you generated from Faro that month. One per order, no matter how many lines it carried: an order with 30 products counts as 1, not 30.\n\nWhat it does NOT count: whatever you ordered by WhatsApp or phone without recording it here, and receptions (those live in Orders).\n\nIf you buy weekly, 4 or 5 a month is normal. If it says 1 and you know you made ten purchases, the figure is not the problem: nine purchases are being decided outside Faro.',
      recap_adoption_title: 'Adoption for the month: how much you followed',
      recap_adoption_body: 'Of the lines Faro put in your cart that month, what share you took — as offered or with the quantity changed. The two raw numbers are right underneath: "You followed 34 of 50 lines".\n\nIt counts proposed lines, not distinct products: if the same SKU appeared in two orders, it counts twice.\n\n90% says you review and accept. 30% says you correct almost everything by hand, and that is not fixed by looking at this screen: it is fixed on the supplier record (lead time, service level).',
      recap_risks_title: 'Risks handled: actions, not stockouts avoided',
      recap_risks_body: 'Lines marked "Order NOW" that you did order within the month. It counts what you did. It is not "stockouts you avoided": we will never see what would have happened without that order, so we do not invent it.\n\nCareful about reading it as an achievement. If it stays high month after month, you are hitting red very often. The healthy pattern is watching it fall while the orders hold: that is ordering in time instead of firefighting.\n\nA 0 alongside orders generated is not a gap: it is the ideal month — you bought without any product reaching urgent.',
      recap_capital_title: 'Capital freed: a subtraction of two measurements',
      recap_capital_body: 'How much the value of your overstocked inventory fell during the month. It is the subtraction of two real snapshots of your stock: the one on day 1 of that month minus the one on day 1 of the next. Nothing modelled.\n\n"Unavailable" here means one of two things, and neither is a zero: one of the two snapshots is missing (you have been measuring for less than two months), or overstock grew instead of falling. An increase is not a saving, and printing 0 would read as "you achieved nothing" when the truth is "this did not happen".',
      recap_managed_title: 'Managed purchases: units × cost',
      recap_managed_body: 'The value of what you ordered: units ordered multiplied by the unit cost you loaded on each SKU. It is money moved — not margin, not sales, and it excludes the lines you dropped from the cart.\n\n"Unavailable" here means something very concrete: no line that month carried a unit cost. It is fixed in one place — load the cost on your SKU records and the next recap comes out in money. Until then we do not fill it with an invented average.',
      hero_title: 'Below it, the running totals',
      hero_body: 'The three big numbers are not for the month: they cover your whole history with Faro, since your first order. That is why they only go up, and why they do not compare with the tiles above.\n\nAlways read them next to the time window on the first one ("since 4 March · 120 days active"). Twelve orders in 40 days is a weekly rhythm; the same twelve in 400 days is something else entirely.',
      hero_orders_title: 'Orders generated (all time)',
      hero_orders_body: 'Every order you have generated from Faro, counted the same way as above: one per order.\n\nUnderneath it are the date of the first one and the days elapsed since. That window is what gives the rest of the screen meaning: many days and few orders means most of your buying is being decided elsewhere, and everything else here will look thin — not because we measure badly, but because there is nothing to measure.',
      hero_risks_title: 'Stockout risks handled (all time)',
      hero_risks_body: 'The total of "Order NOW" lines you have ordered since you started using Faro. Again: recorded actions, not stockouts avoided.\n\nOn its own the number says little; compare it with the orders beside it. 20 orders and 120 risks handled is six emergencies per order: you are buying in firefighting mode. The same count at 20 and 25 says you ordered almost everything before it went red, which is exactly what the stock signal is for.',
      hero_value_title: 'Money managed (all time)',
      hero_value_body: 'The sum of units × unit cost across everything you have ordered. Money your purchases moved, not money saved.\n\nIf instead of an amount you see an amber "total units ordered", it is not a screen fault: none of your orders carried a unit cost. It is the one figure here you can fix today — put the cost on your SKUs and the next order already adds up in money. Past orders keep the cost each one carried, so they are not rewritten.',
      adoption_title: 'The figure that is actually useful',
      adoption_body: 'Out of every hundred lines we put in front of you, how many you took. The card turns green from 70%, amber between 40 and 70, red below 40.\n\nLow does not mean you are disobedient: it means the quantities do not add up for you, and the cause is almost always lead times or service levels that are set wrong. The grey line underneath ("X discarded") is your to-do list: those are the lines you removed from the cart.\n\nIf this card is missing, you have not approved or discarded anything yet.',
      monthly_title: 'Month by month, for the trend',
      monthly_body: 'The same count repeated per month, the last six, newest first. It answers a question that does have an honest answer: are you ordering on time more than you used to, and are you trusting the suggestions more?\n\nA blank row is not an error: it is a month in which you generated no orders. And the current month shows up incomplete, because days are still missing from it.',
      columns_title: 'What each column measures',
      columns_body: 'Month: the calendar month.\nOrders: how many orders you generated.\nStockout risks handled: "Order NOW" lines you ordered; shown in red when there is any.\nManaged value: units × unit cost; it comes out as 0 if your SKUs have no cost loaded.\nAdoption %: accepted ÷ proposed, with "—" when we proposed nothing that month.\nCapital freed: appears only when both inventory snapshots exist; otherwise it says there is not enough history yet rather than inventing the subtraction.',
      orders_link_title: 'See orders and record arrivals',
      orders_link_body: 'This link takes you to where each order lives: what it carried, which supplier, and the button to mark that it arrived.\n\nRecording the arrival is not paperwork. Every reception teaches Faro how long that supplier really takes, and that real time is what later decides when it tells you to order. If you never record arrivals, the system keeps believing the lead time somebody typed in on day one — and that is where half the recommendations that do not add up come from.',
      back_title: 'Back to Inventory',
      back_body: 'It returns you to the stock signal, which is where what to order today is actually decided.\n\nThere is nothing here you can break: this screen only reads and counts, it changes none of your data. Come and go as often as you like.\n\nWhat does move these numbers is on the other side: every order you generate from the stock signal shows up on this screen, and in the following month recap.',
      why_title: 'Why we do not promise you a saving',
      why_body: 'An avoided stockout cannot be measured: it would require knowing what you would have sold with stock that never existed. Anyone who hands you that number is modelling it, not measuring it — and charging you for it all the same.\n\nWhat this screen does let you do is an honest comparison with yourself: if your adoption rises and your handled risks fall without the orders falling, you are buying better. If not, the screen says so without make-up, which is what it is for.',
    },
  },
}
