import type { TourDefinition } from '../types'

export const scenariosTour: TourDefinition = {
  id: 'scenarios-v4',
  route: '/scenarios',
  name: 'name',
  autoStart: true,
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'sc.session', title: 'session_title', body: 'session_body' },
    { anchor: 'sc.builder', title: 'builder_title', body: 'builder_body' },
    { anchor: 'sc.rule', title: 'rule_title', body: 'rule_body' },
    { anchor: 'sc.multiplier', title: 'multiplier_title', body: 'multiplier_body' },
    { anchor: 'sc.scope', title: 'scope_title', body: 'scope_body' },
    { anchor: 'sc.dates', title: 'dates_title', body: 'dates_body' },
    { anchor: 'sc.rule', title: 'delay_title', body: 'delay_body' },
    { anchor: 'sc.rule', title: 'service_title', body: 'service_body' },
    { anchor: 'sc.add_rule', title: 'add_title', body: 'add_body' },
    { anchor: 'sc.run', title: 'run_title', body: 'run_body' },
    { anchor: 'sc.compare', title: 'compare_title', body: 'compare_body' },
    { anchor: 'sc.changes', title: 'changes_title', body: 'changes_body' },
    { anchor: 'sc.save', title: 'save_title', body: 'save_body' },
    { anchor: 'sc.saved', title: 'saved_title', body: 'saved_body' },
    { title: 'safe_title', body: 'safe_body' },
  ],
  copy: {
    es: {
      name: 'Cómo simular un escenario',
      intro_title: 'Probar una decisión antes de que cueste dinero',
      intro_body: '¿Qué pasa con mis compras si la demanda sube un 40%? ¿Si mi proveedor se atrasa una semana? ¿Si hago promoción en diciembre?\n\nAquí lo ves antes de comprometerte. Recalculamos el semáforo completo bajo tu supuesto y te mostramos, producto por producto, qué cambiaría. Nada de esto toca tu inventario ni tus pedidos.',
      session_title: 'Sobre qué predicción estás simulando',
      session_body: 'Un escenario no se calcula en el aire: parte de una predicción ya entrenada y le aplica tus supuestos encima.\n\nEsta lista muestra tus sesiones ya terminadas. Si tienes varias, aquí eliges cuál es la base; si sólo tienes una, ya viene elegida y no tienes que tocar nada.\n\nCambiarla cambia los resultados, porque el punto de partida es otro — y borra la comparación que tuvieras en pantalla, para no dejarte números viejos bajo un título nuevo.',
      builder_title: 'Un escenario es un montón de reglas',
      builder_body: 'Cada regla cambia una sola cosa. Puedes apilar varias para armar una situación completa: «sube la demanda un 30% Y además mi proveedor tarda 5 días más».\n\nEso es justamente lo difícil de estimar de cabeza — dos efectos a la vez, sobre cientos de productos con distintos stocks y tiempos de entrega. Es lo que esta pantalla hace por ti.\n\nEmpiezas con una regla ya puesta, de tipo Cambio de demanda, para que no arranques en blanco.',
      rule_title: 'El menú decide qué campos ves',
      rule_body: 'El desplegable de arriba elige qué cambia esta regla, y con él cambian los campos de abajo.\n\n· Cambio de demanda: multiplica lo que esperamos vender.\n· Promoción: lo mismo, pero sólo entre dos fechas.\n· Atraso de proveedor: le suma días al tiempo de entrega.\n· Nivel de servicio: cambia el colchón contra quedarte sin producto.\n\nCambiar el tipo reinicia los campos de esa regla, así que elige primero el tipo y llena después. La X de la derecha borra la regla completa.',
      multiplier_title: 'El multiplicador: 1.4 es 40% más',
      multiplier_body: 'Es cuánto se mueve la venta esperada. 1.4 = vendes un 40% más. 1 = no cambia nada. Y sí, también sirve para abajo: 0.8 = vendes un 20% menos, que es como pruebas una caída y no sólo un pico.\n\nSe acepta entre 0.01 y 10. Para un supuesto que quieras defender frente a alguien, quédate entre 0.7 y 2; un 5 se puede simular, pero te devuelve un escenario que nadie se va a creer.\n\nCuidado con escribir 40 pensando en «40%»: eso multiplica tu demanda por cuarenta y el resultado no te sirve para nada.',
      dates_title: 'Desde y Hasta: la ventana del pico',
      dates_body: 'Acotan en qué días aplica el multiplicador. Ejemplo: del 24/11 al 02/12 para el fin de semana de descuentos.\n\nEn Cambio de demanda son opcionales: si las dejas vacías, el multiplicador aplica a todo el horizonte pronosticado — o sea, estás diciendo que el cambio llegó para quedarse.\n\nEn Promoción son obligatorias: si las dejas vacías, Simular falla y te lo dice. Es a propósito; una promo sin fechas no es una promo.\n\nLa fecha final no puede ser anterior a la inicial.',
      scope_title: 'SKU y Categoría: a quién le aplica',
      scope_body: 'Con los dos vacíos, la regla aplica a todo tu portafolio. Eso es lo correcto para un supuesto de mercado: «diciembre sube para todo».\n\nEscribe un SKU exacto, el mismo código que usan tus datos, para un solo producto; o una categoría, por ejemplo Bebidas, para un grupo. Llenar uno vacía el otro: una regla apunta a un producto o a una categoría, nunca a los dos.\n\nSi el código o la categoría no coinciden con los tuyos, la regla no da error: simplemente no toca nada, y lo vas a ver en «series ajustadas» arriba de la comparación.',
      delay_title: 'Atraso de proveedor: días de más',
      delay_body: 'Al elegir este tipo, la tarjeta cambia y te pide dos cosas: Días de atraso y Proveedor.\n\nDías de atraso es cuánto se demora de más, sumado al tiempo de entrega que ya tenías. 7 es la semana clásica de aduana; 21 o 30 sirven para el escenario feo del contenedor varado. 0 no cambia nada, y el tope es 365.\n\nProveedor vacío significa que TODOS se atrasan a la vez: el peor caso. Escribe el nombre exacto, tal como aparece en tus productos, para simular sólo a ese — si no coincide, no se atrasa nadie.',
      service_title: 'Nivel de servicio: cuánto colchón',
      service_body: 'Es qué parte de la demanda quieres poder atender sin quedarte sin producto. La lista te deja 90%, 95%, 97% y 99%; si nunca tocas esta regla, tu plan corre al 95%.\n\nSubir a 99% suena bien y es caro: el colchón crece mucho más rápido que el número, y esa plata se queda parada en bodega. Bajar a 90% libera efectivo y te expone a más quiebres.\n\nÚsalo justo para eso: corre 90 y luego 99 y mira, en la comparación de la derecha, cuántas unidades y cuánta plata separan una decisión de la otra.',
      add_title: 'Agregar regla: apilar supuestos',
      add_body: 'Cada clic añade otra regla, y todas se aplican juntas en la misma simulación. Ahí está el valor: «diciembre sube 30% Y mi proveedor tarda 7 días más» es la situación real, y es la que no se estima de cabeza.\n\nLas reglas de demanda se componen cuando se solapan: 1.2 sobre todo el portafolio más 1.5 sobre Bebidas deja Bebidas en 1.8, no en 1.5. Tenlo presente antes de apilar tres multiplicadores encima del mismo producto.\n\nSi te sobra una, la X de su tarjeta la quita.',
      run_title: 'Simular: correr el escenario',
      run_body: 'El botón dice Simular la primera vez y Volver a simular después. Recalcula el semáforo entero con tus supuestos: cobertura, punto de reorden y cantidad sugerida de cada producto.\n\nEl cálculo lo hace el servidor con la misma lógica que usa el semáforo real — no es una aproximación aparte que pueda no coincidir. Tarda unos segundos y no guarda nada, así que córrelo las veces que quieras.\n\nSi te falta un dato obligatorio (las fechas de una promo, por ejemplo), aquí te lo dice en vez de inventárselo.',
      compare_title: 'Plan actual contra escenario',
      compare_body: 'La comparación en agregado: cuántos productos pasan a urgente, cuántas unidades más habría que comprar, cuánto dinero representa. La columna del medio es tu escenario; la última, la diferencia contra hoy.\n\nLéelo como una medida de exposición: si un atraso de 5 días te mueve el 60% del catálogo a urgente, tu operación depende de ese proveedor más de lo que probablemente creías.',
      changes_title: 'Lo que de verdad cambiaría de decisión',
      changes_body: 'Esta es la parte accionable: qué productos concretos cambian de recomendación de compra, y de qué a qué. Cada fila te muestra el antes y el después del semáforo, de la cantidad sugerida, de la venta diaria y del tiempo de entrega.\n\nY si la lista sale vacía, eso también es información valiosa: tu supuesto no mueve la aguja, así que ese riesgo no requiere que hagas nada hoy.',
      save_title: 'Ponle nombre y guárdalo',
      save_body: 'El campo pide un nombre y no puede ir vacío: si le das Guardar en blanco, te avisa y no guarda nada. Ponle uno que se entienda dentro de seis meses — «Black Friday +40%» o «Proveedor X se atrasa 2 semanas», no «prueba 3».\n\nGuardar conserva las reglas, no los resultados. Cuando lo vuelvas a correr, corre contra tus datos de ese día.\n\nEl escenario queda amarrado a la sesión de pronóstico que elegiste arriba: si cambias de sesión, no lo verás en la lista de abajo.',
      saved_title: 'Cargar y borrar los guardados',
      saved_body: 'Cada renglón muestra el nombre y cuántas reglas tiene.\n\nCargar rellena el constructor con esas reglas y corre la simulación de una vez: es la forma rápida de repetir el escenario del año pasado con el inventario de hoy. Ojo, reemplaza lo que tengas armado sin preguntar — guarda antes si te sirve.\n\nEl basurero borra, y te deja unos segundos para Deshacer en el aviso de abajo. Si dejas pasar ese momento, se fue de verdad.',
      safe_title: 'Nada de esto toca tu inventario',
      safe_body: 'Ninguna simulación cambia tu stock, tus pedidos ni el semáforo que ve tu equipo. Es una copia de trabajo.\n\nSi el escenario te convence, la decisión se toma en el Panel de Compras, a mano, como siempre.',
    },
    en: {
      name: 'How to simulate a scenario',
      intro_title: 'Test a decision before it costs money',
      intro_body: 'What happens to my purchasing if demand rises 40%? If my supplier runs a week late? If I run a promotion in December?\n\nSee it here before committing. We recompute the entire stock signal under your assumption and show you, product by product, what would change. None of it touches your inventory or your orders.',
      session_title: 'Which forecast you are simulating against',
      session_body: 'A scenario is not computed from thin air: it starts from an already-trained forecast and applies your assumptions on top.\n\nThis list shows your finished sessions. If you have several, this is where you choose the base; if you only have one, it is already selected and there is nothing to do here.\n\nChanging it changes the results, because the starting point is different — and it clears whatever comparison is on screen, so you are never left with old numbers under a new title.',
      builder_title: 'A scenario is a stack of rules',
      builder_body: 'Each rule changes exactly one thing. Stack several to build a whole situation: "demand up 30% AND my supplier takes 5 days longer".\n\nThat is precisely what is hard to estimate in your head — two effects at once, across hundreds of products with different stock levels and lead times. It is what this screen does for you.\n\nYou start with one rule already in place, of the Demand change type, so you are not staring at a blank panel.',
      rule_title: 'The dropdown decides which fields you see',
      rule_body: 'The dropdown at the top picks what this rule changes, and the fields below change with it.\n\n· Demand change: multiplies what we expect to sell.\n· Promotion: the same, but only between two dates.\n· Supplier delay: adds days to the lead time.\n· Service level: changes the buffer against running out.\n\nSwitching the type resets that rule’s fields, so pick the type first and fill in afterwards. The X on the right deletes the whole rule.',
      multiplier_title: 'The multiplier: 1.4 is 40% more',
      multiplier_body: 'It is how far expected sales move. 1.4 = you sell 40% more. 1 = nothing changes. And yes, it works downwards too: 0.8 = you sell 20% less, which is how you test a slump and not only a peak.\n\nAnything between 0.01 and 10 is accepted. For an assumption you want to defend in front of someone, stay between 0.7 and 2; a 5 will simulate, but it gives you a scenario nobody will believe.\n\nCareful with typing 40 when you mean "40%": that multiplies your demand by forty and the result is of no use at all.',
      dates_title: 'From and To: the window of the peak',
      dates_body: 'They limit which days the multiplier applies to. Example: 24 Nov to 2 Dec for the discount weekend.\n\nOn a Demand change they are optional: leave them empty and the multiplier applies to the whole forecast horizon — that is, you are saying the change is here to stay.\n\nOn a Promotion they are required: leave them empty and Simulate fails and tells you so. That is deliberate; a promotion with no dates is not a promotion.\n\nThe end date cannot be earlier than the start date.',
      scope_title: 'SKU and Category: who it applies to',
      scope_body: 'With both empty, the rule applies to your whole portfolio. That is the right thing for a market-wide assumption: "December lifts everything".\n\nType an exact SKU, the same code your data uses, for a single product; or a category, Drinks for instance, for a group. Filling one clears the other: a rule targets a product or a category, never both.\n\nIf the code or the category does not match yours, the rule does not error: it simply touches nothing, and you will see it in "series adjusted" above the comparison.',
      delay_title: 'Supplier delay: extra days',
      delay_body: 'Pick this type and the card changes: it asks for Extra days and Supplier.\n\nExtra days is how much longer they take, added on top of the lead time you already had. 7 is the classic week stuck at customs; 21 or 30 cover the ugly container-adrift scenario. 0 changes nothing, and the ceiling is 365.\n\nAn empty Supplier means ALL of them run late at once: the worst case. Type the exact name, as it appears on your products, to simulate only that one — if it does not match, nobody runs late.',
      service_title: 'Service level: how much buffer',
      service_body: 'It is the share of demand you want to be able to serve without running out. The list offers 90%, 95%, 97% and 99%; if you never touch this rule, your plan runs at 95%.\n\nRaising it to 99% sounds good and is expensive: the buffer grows much faster than the number, and that money sits idle in the warehouse. Dropping to 90% frees up cash and exposes you to more stockouts.\n\nUse it for exactly that: run 90, then 99, and look at the comparison on the right to see how many units and how much money separate the two decisions.',
      add_title: 'Add rule: stacking assumptions',
      add_body: 'Each click adds another rule, and they all apply together in the same simulation. That is where the value is: "December is up 30% AND my supplier takes 7 days longer" is the real situation, and it is the one you cannot estimate in your head.\n\nDemand rules compound where they overlap: 1.2 across the portfolio plus 1.5 on Drinks leaves Drinks at 1.8, not 1.5. Keep that in mind before stacking three multipliers on the same product.\n\nIf one is surplus, the X on its card removes it.',
      run_title: 'Simulate: run the scenario',
      run_body: 'The button reads Simulate the first time and Run again afterwards. It recomputes the whole stock signal under your assumptions: coverage, reorder point and suggested quantity for every product.\n\nThe server does it with the same logic the real stock signal uses — not a separate approximation that might disagree. It takes a few seconds and saves nothing, so run it as often as you like.\n\nIf a required field is missing (a promotion’s dates, say), it tells you here instead of making something up.',
      compare_title: 'Current plan versus scenario',
      compare_body: 'The comparison in aggregate: how many products turn urgent, how many extra units you would have to buy, how much money that is. The middle column is your scenario; the last one is the difference against today.\n\nRead it as a measure of exposure: if a 5-day delay moves 60% of your catalogue to urgent, your operation depends on that supplier more than you probably thought.',
      changes_title: 'What would actually change',
      changes_body: 'This is the actionable part: which specific products change their purchase recommendation, and from what to what. Each row shows before and after for the stock signal, the suggested quantity, the daily sales and the lead time.\n\nAnd if the list comes back empty, that is valuable too: your assumption does not move the needle, so that risk needs nothing from you today.',
      save_title: 'Give it a name and save it',
      save_body: 'The field wants a name and cannot be left empty: hit Save blank and it warns you and saves nothing. Pick one that still makes sense in six months — "Black Friday +40%" or "Supplier X runs 2 weeks late", not "test 3".\n\nSaving keeps the rules, not the results. When you run it again, it runs against your data on that day.\n\nThe scenario is tied to the forecast session you chose above: switch sessions and it will not appear in the list below.',
      saved_title: 'Loading and deleting the saved ones',
      saved_body: 'Each line shows the name and how many rules it holds.\n\nLoad fills the builder with those rules and runs the simulation in one go: it is the fast way to replay last year’s scenario against today’s inventory. Careful — it replaces whatever you had built without asking, so save first if you still need it.\n\nThe bin deletes, and leaves you a few seconds to Undo in the notice at the bottom. Let that moment pass and it is really gone.',
      safe_title: 'None of this touches your inventory',
      safe_body: 'No simulation changes your stock, your orders, or the stock signal your team sees. It is a working copy.\n\nIf the scenario convinces you, the decision is still made by hand in the purchasing panel, as always.',
    },
  },
}
