import type { TourDefinition } from '../types'

export const scenariosTour: TourDefinition = {
  id: 'scenarios-v3',
  route: '/scenarios',
  name: 'name',
  autoStart: true,
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'sc.session', title: 'session_title', body: 'session_body' },
    { anchor: 'sc.builder', title: 'builder_title', body: 'builder_body' },
    { anchor: 'sc.rule', title: 'rule_title', body: 'rule_body' },
    { anchor: 'sc.run', title: 'run_title', body: 'run_body' },
    { anchor: 'sc.compare', title: 'compare_title', body: 'compare_body' },
    { anchor: 'sc.changes', title: 'changes_title', body: 'changes_body' },
    { anchor: 'sc.save', title: 'save_title', body: 'save_body' },
    { title: 'safe_title', body: 'safe_body' },
  ],
  copy: {
    es: {
      name: 'Cómo simular un escenario',
      intro_title: 'Probar una decisión antes de que cueste dinero',
      intro_body: '¿Qué pasa con mis compras si la demanda sube un 40%? ¿Si mi proveedor se atrasa una semana? ¿Si hago promoción en diciembre?\n\nAquí lo ves antes de comprometerte. Recalculamos el semáforo completo bajo tu supuesto y te mostramos, producto por producto, qué cambiaría. Nada de esto toca tu inventario ni tus pedidos.',
      session_title: 'Sobre qué predicción estás simulando',
      session_body: 'Un escenario no se calcula en el aire: parte de una predicción ya entrenada y le aplica tus supuestos encima.\n\nSi tienes varias sesiones entrenadas, aquí eliges cuál es la base. Cambiarla cambia los resultados, porque el punto de partida es otro.',
      builder_title: 'Un escenario es un montón de reglas',
      builder_body: 'Cada regla cambia una sola cosa. Puedes apilar varias para armar una situación completa: «sube la demanda un 30% Y además mi proveedor tarda 5 días más».\n\nEso es justamente lo difícil de estimar de cabeza — dos efectos a la vez, sobre cientos de productos con distintos stocks y tiempos de entrega. Es lo que esta pantalla hace por ti.',
      rule_title: 'Los cuatro tipos de regla',
      rule_body: 'Cambio de demanda: multiplica lo que predecimos. 1.4 = vende un 40% más.\n\nPromoción: igual, pero sólo entre dos fechas. Para un pico que empieza y termina.\n\nAtraso de proveedor: le suma días al tiempo de entrega. Sube el punto de reorden, porque tienes que cubrir más días esperando.\n\nNivel de servicio: qué tan poco quieres arriesgarte a quedarte sin stock. Subirlo compra más colchón — y más inventario parado.\n\nCada regla puede aplicarse a todo el portafolio, a una categoría o a un solo SKU. Si dejas SKU y categoría vacíos, aplica a todo.',
      run_title: 'Correr la simulación',
      run_body: 'Recalculamos el semáforo entero con tus supuestos: cobertura, punto de reorden y cantidad sugerida de cada producto.\n\nEl cálculo lo hace el servidor con la misma lógica que usa el semáforo real — no es una aproximación aparte que pueda no coincidir. Puedes correrlo las veces que quieras.',
      compare_title: 'Plan actual contra escenario',
      compare_body: 'La comparación en agregado: cuántos productos pasan a urgente, cuántas unidades más habría que comprar, cuánto dinero representa.\n\nLéelo como una medida de exposición: si un atraso de 5 días te mueve el 60% del catálogo a urgente, tu operación depende de ese proveedor más de lo que probablemente creías.',
      changes_title: 'Lo que de verdad cambiaría de decisión',
      changes_body: 'Esta es la parte accionable: qué productos concretos cambian de recomendación de compra, y de qué a qué.\n\nY si la lista sale vacía, eso también es información valiosa: tu supuesto no mueve la aguja, así que ese riesgo no requiere que hagas nada hoy.',
      save_title: 'Guardar para volver a correrlo',
      save_body: 'Guardar el escenario conserva las reglas, no los resultados. Cuando lo vuelvas a correr, lo hace contra tus datos actuales.\n\nEso es lo que lo hace útil de forma recurrente: «Black Friday +40%» sirve todos los años, y cada año responde con el inventario que tienes en ese momento.',
      safe_title: 'Nada de esto toca tu inventario',
      safe_body: 'Ninguna simulación cambia tu stock, tus pedidos ni el semáforo que ve tu equipo. Es una copia de trabajo.\n\nSi el escenario te convence, la decisión se toma en el Panel de Compras, a mano, como siempre.',
    },
    en: {
      name: 'How to simulate a scenario',
      intro_title: 'Test a decision before it costs money',
      intro_body: 'What happens to my purchasing if demand rises 40%? If my supplier runs a week late? If I run a promotion in December?\n\nSee it here before committing. We recompute the entire stock signal under your assumption and show you, product by product, what would change. None of it touches your inventory or your orders.',
      session_title: 'Which forecast you are simulating against',
      session_body: 'A scenario is not computed from thin air: it starts from an already-trained forecast and applies your assumptions on top.\n\nIf you have several trained sessions, this is where you choose the base. Changing it changes the results, because the starting point is different.',
      builder_title: 'A scenario is a stack of rules',
      builder_body: 'Each rule changes exactly one thing. Stack several to build a whole situation: "demand up 30% AND my supplier takes 5 days longer".\n\nThat is precisely what is hard to estimate in your head — two effects at once, across hundreds of products with different stock levels and lead times. It is what this screen does for you.',
      rule_title: 'The four rule types',
      rule_body: 'Demand change: multiplies what we forecast. 1.4 = sells 40% more.\n\nPromotion: the same, but only between two dates. For a peak that starts and ends.\n\nSupplier delay: adds days to the lead time. It raises the reorder point, because you have to cover more waiting days.\n\nService level: how little you want to risk running out. Raising it buys more buffer — and more idle inventory.\n\nEach rule can apply to the whole portfolio, one category, or a single SKU. Leave SKU and category empty and it applies to everything.',
      run_title: 'Run the simulation',
      run_body: 'We recompute the whole stock signal under your assumptions: coverage, reorder point and suggested quantity for every product.\n\nThe server does it with the same logic the real stock signal uses — not a separate approximation that might disagree. Run it as often as you like.',
      compare_title: 'Current plan versus scenario',
      compare_body: 'The comparison in aggregate: how many products turn urgent, how many extra units you would have to buy, how much money that is.\n\nRead it as a measure of exposure: if a 5-day delay moves 60% of your catalogue to urgent, your operation depends on that supplier more than you probably thought.',
      changes_title: 'What would actually change',
      changes_body: 'This is the actionable part: which specific products change their purchase recommendation, and from what to what.\n\nAnd if the list comes back empty, that is valuable too: your assumption does not move the needle, so that risk needs nothing from you today.',
      save_title: 'Save it to run again',
      save_body: 'Saving a scenario keeps the rules, not the results. When you run it again, it runs against your current data.\n\nThat is what makes it useful repeatedly: "Black Friday +40%" works every year, and every year it answers with the inventory you have at that moment.',
      safe_title: 'None of this touches your inventory',
      safe_body: 'No simulation changes your stock, your orders, or the stock signal your team sees. It is a working copy.\n\nIf the scenario convinces you, the decision is still made by hand in the purchasing panel, as always.',
    },
  },
}
