import type { TourDefinition } from '../types'

export const sessionsTour: TourDefinition = {
  id: 'sessions-v2',
  route: '/historial',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'ses.row', title: 'row_title', body: 'row_body' },
    { anchor: 'ses.name', title: 'name_col_title', body: 'name_col_body' },
    { anchor: 'ses.status', title: 'status_title', body: 'status_body' },
    { anchor: 'ses.dataset', title: 'dataset_title', body: 'dataset_body' },
    { anchor: 'ses.created', title: 'created_title', body: 'created_body' },
    { anchor: 'ses.horizon', title: 'horizon_title', body: 'horizon_body' },
    { anchor: 'ses.granularity', title: 'granularity_title', body: 'granularity_body' },
    { anchor: 'ses.skus', title: 'skus_title', body: 'skus_body' },
    { anchor: 'ses.rename', title: 'rename_title', body: 'rename_body' },
    { anchor: 'ses.delete', title: 'delete_title', body: 'delete_body' },
  ],
  copy: {
    es: {
      name: 'Cómo funciona el historial',
      intro_title: 'Cada vez que actualizaste, aquí queda',
      intro_body: 'Esta lista no es un registro decorativo. Cada fila es el cálculo completo que Faro hizo con tus ventas, y es la pieza a la que apunta todo lo demás.\n\nEl semáforo de stock, las proyecciones por producto y los escenarios se calculan siempre a partir de una de estas filas. Cuando dos pantallas te muestran números distintos, casi siempre están leyendo actualizaciones distintas.\n\nVamos columna por columna: cada una responde una pregunta concreta cuando algo no te cuadra.',
      row_title: 'Una fila es un cálculo entero',
      row_body: 'Dentro de cada una va todo junto: el archivo que subiste, los ajustes con que se calculó, los modelos que ganaron y la proyección de cada producto.\n\nHaz clic en cualquier parte de una fila completada y se abren sus resultados producto por producto. Las que no terminaron no abren nada, porque no hay resultados que ver — el cursor te lo avisa antes de hacer clic.\n\nLos dos iconos de la derecha son la excepción: ahí el clic no abre la fila, actúa sobre ella.',
      name_col_title: 'Nombre: la etiqueta que le pusiste',
      name_col_body: 'Es texto libre tuyo, no lo genera el sistema, y es el nombre con el que esta actualización aparece en el selector del semáforo, en los escenarios y en el analista. Si allá no distingues cuál es cuál, el problema empezó en esta columna.\n\nUno útil dice archivo, granularidad y horizonte: «Ventas 2024-2026 · semanal · 12 semanas». Uno inútil es «prueba», «demo1» o «final2»: dentro de tres meses vas a tener cuatro filas y ninguna pista de en qué se diferencian.',
      status_title: 'Estado: cuál sirve y cuál no',
      status_body: 'Completada es la única que sirve para trabajar: es la que puedes elegir en el semáforo, en los escenarios y en el analista. Las demás no aparecen en esos selectores.\n\nEn cola y Calculando van en camino — el trabajo corre por detrás y puedes irte de esta pantalla sin cancelar nada.\n\nBorrador, Datos cargados, Columnas configuradas y las demás son sesiones a medio configurar: nunca se llegaron a calcular.\n\nFallida no se borra sola a propósito: la fila se queda para que veas cuál archivo y cuáles ajustes se rompieron.',
      dataset_title: 'Archivo: de dónde salió cada número',
      dataset_body: 'El nombre del archivo de ventas con el que se calculó esta fila. Es la trazabilidad: cuando una proyección se ve rara, aquí ves con qué datos se hizo antes de discutir el resultado.\n\nUn guion aquí significa que la sesión nunca llegó a tener datos cargados.\n\nVer varias filas del mismo archivo es normal y sano — una diaria, otra semanal, otra con más horizonte — porque cambiar esos ajustes cambia los resultados. Por eso el nombre importa: el archivo solo no las distingue.',
      created_title: 'Creada: qué tan vieja es esta foto',
      created_body: 'La fecha en que se creó la sesión. Los resultados no se actualizan solos: una fila de hace tres meses sigue proyectando con las ventas que tenía ese día, aunque desde entonces hayas vendido de otra forma.\n\nRegla simple: si la fila que alimenta tu semáforo tiene más de un mes, súbele el archivo nuevo y corre otra. Comparar la vieja con la nueva es además la única forma honesta de ver si tu demanda cambió o si sólo cambió el modelo.',
      horizon_title: 'Horizonte: cuántos periodos hacia adelante',
      horizon_body: 'Cuántos periodos proyectó esta actualización, contados en la granularidad de la fila. 12 con granularidad semanal son tres meses; 12 con granularidad mensual son un año.\n\nLo que necesitas es que cubra tu peor tiempo de entrega con holgura: si tu proveedor tarda 45 días, un horizonte de 4 semanas te deja decidiendo a ciegas justo en el tramo que importa.\n\nEstirarlo tampoco es gratis: mientras más lejos, más ancha la incertidumbre. Pedir 52 semanas para comprar con 30 días de plazo sólo agrega ruido.\n\nUn guion es una fila que nunca llegó a calcularse: todavía no tiene horizonte.',
      granularity_title: 'Granularidad: el tamaño del periodo',
      granularity_body: 'Si esta actualización agrupó tus ventas por día, por semana o por mes. No es un detalle cosmético: cambia el cálculo y cambia el gráfico.\n\nDiaria sólo tiene sentido si vendes casi todos los días de casi todos los productos; con ventas salteadas, la serie se llena de ceros y el pronóstico se vuelve inestable.\n\nSemanal es la opción sensata para la mayoría de distribuidores. Mensual sirve para planear compras grandes o importaciones, pero es demasiado gruesa para decidir el pedido de esta semana.\n\nAquí también un guion quiere decir que la fila nunca se calculó.',
      skus_title: 'SKUs: cuántos productos entraron',
      skus_body: 'Cuántos productos distintos quedaron dentro del cálculo. Es la columna que más rápido delata un problema: si esperabas 800 y ves 300, no falló el pronóstico, falló la entrada.\n\nLas causas de siempre: el archivo venía filtrado, la columna de producto quedó mal mapeada al subirlo, o productos con muy poca historia se quedaron fuera por no tener suficientes datos.\n\nUn guion significa que la fila nunca terminó de calcular, así que todavía no hay productos que contar.',
      rename_title: 'El lápiz: renombrar es barato',
      rename_body: 'Abre el nombre para editarlo ahí mismo. Enter guarda, Escape cancela, y el check y la equis de al lado hacen lo mismo con el ratón.\n\nSólo cambia la etiqueta: nada se recalcula, ningún número se mueve y nada de lo que apunta a esta fila se rompe. Es la operación más segura de la pantalla, así que úsala apenas veas un nombre que no dice nada.\n\nSi no ves ningún icono en esta columna, tu usuario es de sólo lectura: puedes mirar el historial pero no tocarlo.',
      delete_title: 'El basurero: esto no tiene deshacer',
      delete_body: 'Te pide confirmación y después se lleva la fila entera: sus proyecciones por producto, sus métricas de precisión, sus registros de entrenamiento y los archivos que generó. No hay deshacer.\n\nLo que NO se borra: el archivo de ventas que subiste. Ese vive aparte y puedes crear otra actualización con él cuando quieras. Las conversaciones del analista tampoco se borran, pero pierden esa base y vuelven a responder en modo general.\n\nLo que sí queda cojo: el semáforo o un escenario que apuntaban aquí — hay que recalcular. Mientras una fila está Calculando el icono está apagado, porque el trabajo sigue corriendo.',
    },
    en: {
      name: 'How the history works',
      intro_title: 'Every update you ran stays here',
      intro_body: 'This list is not a decorative log. Each row is the complete calculation Faro ran on your sales, and it is the piece everything else points at.\n\nThe stock signal, the per-product projections and the scenarios are always computed from one of these rows. When two screens show you different numbers, they are almost always reading different updates.\n\nWe will go column by column: each one answers a concrete question when something does not add up.',
      row_title: 'A row is one whole calculation',
      row_body: 'Each one bundles it all together: the file you uploaded, the settings it was computed with, the models that won, and the projection for every product.\n\nClick anywhere on a completed row and its product-by-product results open. The ones that did not finish open nothing, because there are no results to see — the cursor tells you before you click.\n\nThe two icons on the right are the exception: there, a click does not open the row, it acts on it.',
      name_col_title: 'Name: the label you gave it',
      name_col_body: 'It is free text of yours, not generated by the system, and it is the name this update carries in the stock-signal picker, in scenarios and in the analyst. If you cannot tell them apart over there, the problem started in this column.\n\nA useful one states file, granularity and horizon: "Sales 2024-2026 · weekly · 12 weeks". A useless one is "test", "demo1" or "final2": three months from now you will have four rows and no clue what separates them.',
      status_title: 'Status: which one is usable and which is not',
      status_body: 'Completed is the only one you can work from: it is the one you can pick in the stock signal, in scenarios and in the analyst. The rest do not appear in those pickers.\n\nQueued and Calculating are on their way — the work runs in the background and you can leave this screen without cancelling anything.\n\nDraft, Data loaded, Columns configured and the others are half-configured sessions: they were never actually calculated.\n\nFailed is deliberately not cleaned up: the row stays so you can see which file and which settings broke.',
      dataset_title: 'File: where each number came from',
      dataset_body: 'The name of the sales file this row was computed from. This is the traceability: when a projection looks odd, this is where you see what data produced it before arguing with the result.\n\nA dash here means the session never got as far as having data loaded.\n\nSeveral rows from the same file is normal and healthy — one daily, one weekly, one with a longer horizon — because changing those settings changes the results. Which is why the name matters: the file alone does not tell them apart.',
      created_title: 'Created: how old this snapshot is',
      created_body: 'The date the session was created. Results do not refresh themselves: a row from three months ago still projects with the sales it had that day, however differently you have sold since.\n\nSimple rule: if the row feeding your stock signal is more than a month old, upload the fresh file and run another. Comparing the old one with the new one is also the only honest way to see whether your demand changed or only the model did.',
      horizon_title: 'Horizon: how many periods ahead',
      horizon_body: 'How many periods this update projected, counted in the row granularity. 12 at weekly granularity is three months; 12 at monthly granularity is a year.\n\nWhat you need is for it to cover your worst lead time with room to spare: if your supplier takes 45 days, a 4-week horizon leaves you deciding blind over exactly the stretch that matters.\n\nStretching it is not free either: the further out, the wider the uncertainty. Asking for 52 weeks to buy on 30-day terms only adds noise.\n\nA dash is a row that never got calculated: it has no horizon yet.',
      granularity_title: 'Granularity: the size of the period',
      granularity_body: 'Whether this update grouped your sales by day, by week or by month. It is not cosmetic: it changes the calculation and it changes the chart.\n\nDaily only makes sense if you sell almost every day for almost every product; with scattered sales the series fills with zeros and the forecast turns unstable.\n\nWeekly is the sensible option for most distributors. Monthly is fine for planning big buys or imports, but it is far too coarse to decide this week order.\n\nHere too, a dash means the row was never calculated.',
      skus_title: 'SKUs: how many products went in',
      skus_body: 'How many distinct products ended up inside the calculation. It is the column that exposes a problem fastest: if you expected 800 and see 300, the forecast did not fail, the input did.\n\nThe usual causes: the file came pre-filtered, the product column was mapped wrong on upload, or products with very little history were left out for not having enough data.\n\nA dash means the row never finished calculating, so there are no products to count yet.',
      rename_title: 'The pencil: renaming is cheap',
      rename_body: 'It opens the name for editing right there. Enter saves, Escape cancels, and the tick and cross beside it do the same with the mouse.\n\nIt only changes the label: nothing is recomputed, no number moves, and nothing that points at this row breaks. It is the safest operation on the screen, so use it the moment you see a name that says nothing.\n\nIf you see no icons in this column, your user is read-only: you can look at the history but not touch it.',
      delete_title: 'The bin: this one has no undo',
      delete_body: 'It asks for confirmation and then takes the whole row: its per-product projections, its accuracy metrics, its training logs and the files it generated. There is no undo.\n\nWhat is NOT deleted: the sales file you uploaded. That lives separately and you can build another update from it whenever you want. Analyst conversations are not deleted either, but they lose that base and go back to answering in general mode.\n\nWhat is left limping: a stock signal or a scenario that pointed here — those must be recalculated. While a row is Calculating the icon is greyed out, because the job is still running.',
    },
  },
}
