import type { TourDefinition } from '../types'

export const suppliersTour: TourDefinition = {
  id: 'suppliers-v2',
  route: '/proveedores',
  name: 'name',
  steps: [
    { title: 'intro_title', body: 'intro_body' },
    { anchor: 'sup.add', title: 'form_title', body: 'form_body' },
    { anchor: 'sup.add', title: 'formdays_title', body: 'formdays_body' },
    { anchor: 'sup.leadtime', title: 'leadtime_title', body: 'leadtime_body' },
    { anchor: 'sup.learning', title: 'learning_title', body: 'learning_body' },
    { anchor: 'sup.contact', title: 'contact_title', body: 'contact_body' },
    { anchor: 'sup.pricebreaks', title: 'breaks_title', body: 'breaks_body' },
    { anchor: 'sup.scorecard', title: 'scorecard_title', body: 'scorecard_body' },
  ],
  copy: {
    es: {
      name: 'Por qué el proveedor manda',
      intro_title: 'Doce fichas que gobiernan dos mil productos',
      intro_body: 'El tiempo de entrega es el dato que más mueve tus compras, y casi nunca lo tienes producto por producto: lo tienes por proveedor. Por eso se configura una vez aquí y rige todo el catálogo de ese proveedor.\n\nSi a un producto le pusiste su propio tiempo de entrega a mano, ese gana. Lo de esta pantalla es el valor de fondo para todos los demás — que suelen ser casi todos.',
      form_title: 'Crear un proveedor: el nombre es la llave',
      form_body: 'Este botón abre el formulario. Nombre es el único obligatorio, y es el más delicado: tiene que ser el MISMO que aparece en la columna de proveedor de tus productos. «Distribuidora Nacional S.A.» y «Dist. Nacional» son dos proveedores distintos para nosotros, y una orden de compra del segundo se queda sin destinatario.\n\nCorreo: la dirección de compras, no la de facturación — es a donde llega la orden en PDF.\n\nTeléfono y WhatsApp: con código de país, así: +506 8888 8888. Un número local sin el código no sale.\n\nCondiciones de pago y Notas son para ti y para el PDF; no cambian ningún cálculo.',
      formdays_title: 'Días de entrega y variabilidad, en el formulario',
      formdays_body: 'Días de entrega es lo que tarda desde que le pides hasta que te llega. Cuenta días de calendario, puerta a puerta, incluyendo aduana: para un local suelen ser 5 a 10; para importación, 30 a 60. Viene con 15 puesto, que es nuestra suposición, no tu dato — cámbialo.\n\nVariabilidad es cuánto se le mueve ese número. Si dice 15 pero a veces llega en 18, pon 3. Si no tienes idea, deja el 3 que viene y déjanos aprenderlo.\n\nUn ±0 dice «este proveedor nunca falla» y hace que Faro no te deje colchón. Casi nadie merece un 0.',
      leadtime_title: 'Los días, y qué tan puntual es',
      leadtime_body: 'Los días entran dos veces en el cálculo: en lo que vas a vender mientras el pedido viaja, y en el tamaño del colchón. Ponerlos cortos te deja sin producto; ponerlos largos te llena la bodega de plata parada.\n\nLa columna de al lado es la variabilidad. ±2 días es un proveedor con el que puedes planear. ±10 te obliga a cargar colchón aunque su promedio se vea bien, y eso lo pagas tú: un proveedor impuntual sale caro aunque su precio sea el mejor.\n\nEl lápiz de la derecha reabre el formulario para corregir cualquiera de los dos.',
      learning_title: 'Lo que aprendemos de las llegadas',
      learning_body: 'Cada vez que registras la recepción de un pedido medimos cuánto tardó de verdad. Cuando juntamos suficientes, dejamos de usar el número que escribiste y planeamos con el que se ve en tus entregas.\n\nEsta columna te dice en qué punto va, con el número exacto: cuántas recepciones llevas, cuántas faltan para que el aprendizaje mande, y cuál es el promedio aprendido cuando ya manda. Son pocas, se llega rápido.\n\nEs la razón para registrar recepciones aunque cueste el minuto: es lo único que convierte un supuesto en un dato tuyo.',
      contact_title: 'Sin correo ni WhatsApp, el pedido no sale',
      contact_body: 'Cuando envías una orden desde Faro, viaja por correo o por WhatsApp. Un proveedor que no tenga ninguno de los dos queda fuera del envío: te avisamos que se omitió, pero la orden de ese proveedor no llegó a ninguna parte. Un guion en esta columna es justamente eso esperando pasar.\n\nY si el nombre del proveedor en tus productos no corresponde a ninguna ficha de aquí, la orden ni siquiera sabe a quién va: aparece como no resuelta.\n\nCon uno de los dos canales lleno basta. Si un proveedor te importa, dale al menos ese.',
      breaks_title: 'Escalas de precio por volumen',
      breaks_body: 'El botón de la etiqueta abre las escalas de ese proveedor. Cada renglón es un escalón y se llena con tres datos: SKU (el código exacto del producto), Cantidad mínima (desde cuántas unidades aplica) y Precio unitario (lo que cuesta CADA unidad a partir de ahí, no el total). Notas es opcional.\n\nEjemplo de una lista real: SKU-001 · 100 · 1.200, y otro renglón SKU-001 · 500 · 1.050. Un escalón por tramo, del mismo producto, y sin repetir la cantidad.\n\nSi no se los das, no podemos verlos por ti: la app pedirá la cantidad correcta, pero al precio de lista, y el descuento que ya negociaste se queda sin usar.',
      scorecard_title: 'Cómo se ha portado, con números',
      scorecard_body: 'La ficha comparativa mide a cada proveedor por lo que hizo: recepciones registradas, tiempo de entrega real contra el declarado, puntualidad, qué tan completas llegaron las entregas y cuánto le compraste.\n\nTambién marca las desviaciones: cuando sus últimas entregas se salen de su propio historial, te lo dice antes de que lo sientas en la bodega.\n\nSe llena sola con las recepciones que registras, así que al principio estará vacía. Es con lo que se entra a negociar precio, y con lo que decides a quién le confías el producto que no te puedes dar el lujo de que falte.',
    },
    en: {
      name: 'Why the supplier decides',
      intro_title: 'A dozen records that govern two thousand products',
      intro_body: 'Lead time is the input that moves your purchasing most, and you almost never have it product by product: you have it per supplier. So it is set once here and governs that supplier\'s whole catalogue.\n\nIf you set a lead time by hand on a product, that one wins. What lives on this screen is the underlying value for everything else — which is usually almost everything.',
      form_title: 'Creating a supplier: the name is the key',
      form_body: 'This button opens the form. Name is the only required field, and the most delicate one: it has to be the SAME name that appears in the supplier column of your products. "National Distributor Inc." and "Nat. Distributor" are two different suppliers to us, and an order for the second one ends up with no addressee.\n\nEmail: the purchasing address, not the billing one — that is where the order PDF lands.\n\nPhone and WhatsApp: with country code, like this: +506 8888 8888. A local number without it will not send.\n\nPayment terms and Notes are for you and for the PDF; they change no calculation.',
      formdays_title: 'Lead time and variability, on the form',
      formdays_body: 'Lead time is how long they take from your order to the delivery. Count calendar days, door to door, customs included: a local supplier is usually 5 to 10; an import leg, 30 to 60. It arrives pre-filled with 15, which is our assumption and not your figure — change it.\n\nVariability is how much that number swings. If they say 15 but sometimes arrive in 18, put 3. If you have no idea, leave the 3 and let us learn it.\n\nA ±0 claims "this supplier never fails" and makes Faro leave you no buffer. Almost nobody deserves a 0.',
      leadtime_title: 'The days, and how punctual they are',
      leadtime_body: 'The days enter the calculation twice: in what you will sell while the order is in transit, and in the size of the buffer. Set them too short and you run out; set them too long and the warehouse fills up with idle money.\n\nThe column beside it is variability. ±2 days is a supplier you can plan around. ±10 forces you to carry buffer even when their average looks fine, and you are the one who pays for it: an unreliable supplier is expensive even at the best price.\n\nThe pencil on the right reopens the form to correct either of them.',
      learning_title: 'What we learn from arrivals',
      learning_body: 'Every time you record the reception of an order we measure how long it actually took. Once we have enough, we stop using the number you typed and plan with the one your deliveries show.\n\nThis column tells you where that stands, with the exact figures: how many receptions you have, how many are still missing before the learned value takes over, and what that learned average is once it does. It is a small number; you get there quickly.\n\nIt is the reason to record receptions even when it costs you the minute: it is the only thing that turns an assumption into a figure of your own.',
      contact_title: 'With no email and no WhatsApp, the order never leaves',
      contact_body: 'When you send an order from Faro it travels by email or by WhatsApp. A supplier with neither is left out of the send: we tell you it was skipped, but that supplier\'s order went nowhere. A dash in this column is exactly that waiting to happen.\n\nAnd if the supplier name on your products matches no record here, the order does not even know who it is for: it comes back as unresolved.\n\nOne of the two channels filled in is enough. If a supplier matters to you, give it at least that.',
      breaks_title: 'Volume price breaks',
      breaks_body: 'The tag button opens that supplier\'s tiers. Each line is one tier and takes three figures: SKU (the exact product code), Min. quantity (from how many units it applies) and Unit price (what EACH unit costs from there on, not the total). Notes is optional.\n\nStraight off a real price list: SKU-001 · 100 · 1,200, then a second line SKU-001 · 500 · 1,050. One line per bracket, same product, never repeating a quantity.\n\nIf you do not give them to us, we cannot see them for you: the app will order the right quantity, but at list price, and the discount you already negotiated goes unused.',
      scorecard_title: 'How they have behaved, in numbers',
      scorecard_body: 'The comparison sheet measures each supplier by what they did: receptions recorded, real lead time against the declared one, punctuality, how complete the deliveries arrived and how much you bought from them.\n\nIt also flags deviations: when their recent deliveries drift out of their own history, it says so before you feel it in the warehouse.\n\nIt fills itself from the receptions you record, so it starts out empty. That is what you walk into a price negotiation with, and what you use to decide who gets the product you cannot afford to be out of.',
    },
  },
}
