"""
Physical stock count — count the warehouse with a phone, compare with the
system, apply the differences.

POST   /inventory/stock-counts                       — open a count session
GET    /inventory/stock-counts                       — list counts
GET    /inventory/stock-counts/{id}                  — one count with its lines
PUT    /inventory/stock-counts/{id}/lines            — record a scan / manual quantity
DELETE /inventory/stock-counts/{id}/lines/{sku}      — remove a line (open counts)
POST   /inventory/stock-counts/{id}/close            — finish counting
GET    /inventory/stock-counts/{id}/preview          — differences with value impact
POST   /inventory/stock-counts/{id}/apply            — write the differences, once
POST   /inventory/stock-counts/{id}/cancel           — discard the count

The barcode lookup (`GET /inventory/stock/lookup`) lives in inventory.py, ahead
of `/stock/{sku}`, which would otherwise swallow it.
"""

from typing import Literal, Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, Field

from backend.activity.events import record_event
from backend.auth.guards import CurrentUser, get_current_user, require_analyst_or_above
from backend.inventory import stock_count_service as svc
from backend.schemas.common import ok

router = APIRouter(prefix="/inventory/stock-counts", tags=["inventory"])


class CountCreate(BaseModel):
    warehouse: Optional[str] = Field(default=None, max_length=100)
    scope_category: Optional[str] = Field(default=None, max_length=100)
    scope_supplier: Optional[str] = Field(default=None, max_length=200)
    notes: Optional[str] = Field(default=None, max_length=500)


class CountLineUpsert(BaseModel):
    sku: str = Field(min_length=1, max_length=200)
    quantity: float = Field(ge=0, le=svc.MAX_QTY)
    # 'add' accumulates (scanning the same product twice counts two units);
    # 'set' replaces the counted total (the stepper, a correction).
    mode: Literal["add", "set"] = "add"
    source: Literal["scan", "manual"] = "manual"
    # Generated by the phone per scan, so a retried or replayed request is a no-op.
    client_ref: Optional[str] = Field(default=None, max_length=100)


class CountApply(BaseModel):
    # Omitted = every line; a list = only those SKUs (partial apply).
    skus: Optional[list[str]] = Field(default=None, max_length=5000)


@router.post("", status_code=201)
def create_count(body: CountCreate, user: CurrentUser = Depends(require_analyst_or_above)):
    """Open a count session for one warehouse, optionally scoped to a category or supplier."""
    return ok(svc.create_count(
        user.tenant_id, user.user_id, body.warehouse,
        scope_category=body.scope_category, scope_supplier=body.scope_supplier,
        notes=body.notes,
    ))


@router.get("")
def list_counts(
    status: Optional[Literal["open", "closed", "applied", "cancelled"]] = Query(default=None),
    limit: int = Query(default=50, ge=1, le=200),
    user: CurrentUser = Depends(get_current_user),
):
    """List stock counts, newest first, with how many products each holds."""
    return ok(svc.list_counts(user.tenant_id, status=status, limit=limit))


@router.get("/{count_id}")
def get_count(count_id: str, user: CurrentUser = Depends(get_current_user)):
    """One count with every line (counted quantity next to the system quantity at the first scan)."""
    return ok(svc.get_count(user.tenant_id, count_id))


@router.put("/{count_id}/lines")
def upsert_line(
    count_id: str, body: CountLineUpsert,
    user: CurrentUser = Depends(require_analyst_or_above),
):
    """Record units of a SKU in an open count. mode 'add' (default) accumulates, 'set' replaces the counted total; a repeated client_ref is ignored."""
    return ok(svc.upsert_line(
        user.tenant_id, count_id, user.user_id, body.sku, body.quantity,
        mode=body.mode, source=body.source, client_ref=body.client_ref,
    ))


@router.delete("/{count_id}/lines/{sku}", status_code=204)
def delete_line(count_id: str, sku: str, user: CurrentUser = Depends(require_analyst_or_above)):
    """Remove one SKU from an open count."""
    svc.delete_line(user.tenant_id, count_id, sku)


@router.post("/{count_id}/close")
def close_count(count_id: str, user: CurrentUser = Depends(require_analyst_or_above)):
    """Finish counting. A closed count accepts no more lines and can be reviewed and applied."""
    return ok(svc.close_count(user.tenant_id, count_id, user.user_id))


@router.get("/{count_id}/preview")
def preview_count(count_id: str, user: CurrentUser = Depends(get_current_user)):
    """Differences between counted and system quantity, largest value impact first. A SKU with no unit cost has a null value impact."""
    return ok(svc.preview(user.tenant_id, count_id))


@router.post("/{count_id}/apply")
def apply_count(
    count_id: str, body: Optional[CountApply] = None,
    user: CurrentUser = Depends(require_analyst_or_above),
):
    """Write the differences into stock, exactly once, and record each adjustment with reason 'physical_count'. Omit skus to apply every line; a list applies only those. All or nothing."""
    result = svc.apply_count(
        user.tenant_id, count_id, user.user_id,
        skus=body.skus if body else None,
    )
    record_event(
        user.tenant_id, user.user_id, "data.stock_count_applied",
        resource=count_id,
        details={
            "warehouse": result["warehouse"],
            "lines":     result["lines_adjusted"],
            "units":     result["units_added"] + result["units_removed"],
        },
    )
    return ok(result)


@router.post("/{count_id}/cancel")
def cancel_count(count_id: str, user: CurrentUser = Depends(require_analyst_or_above)):
    """Discard an open or closed count. Stock is not changed."""
    return ok(svc.cancel_count(user.tenant_id, count_id, user.user_id))
